### ISSUE TITLE
sfdx: hardis:project:fix:v53flexipages Doesn't assign identifiers to dynamic form fields 

### ISSUE THREAD

**Issue by GodertC** [hardisgroupcom/sfdx-hardis#172]
As the title says, after using the hardis:project:fix:v53flexipages I still encountered push issues, fields used in dynamic forms also need identifiers which are not being assigned yet with this command.

**Comment by nvuillam** [comment]
Please could you share the XML of a flexipage that is not completely migrated to v53 format ?

**Comment by GodertC** [comment]
@nvuillam Sorry I can't. However none of the Fielditems got an identifier and do require one when they are being used in dynamic forms. I've added them by hand and after doing that the push was succesfull

**Comment by nvuillam** [comment]
@GodertC maybe just a part of the XML that is not migrated correctly, and after anonymizing the identifiers related to your product/client  ?

That would allow me to provide you a fix ^^

**Comment by nvuillam** [comment]
This command is probably not needed anymore :)
