### ISSUE TITLE
Export files from Org returns no files

### ISSUE THREAD

**Issue by michael-uls33** [hardisgroupcom/sfdx-hardis#214]
Steps to reproduce: 
1) Authenticate and Login to org 
2) create export config.json with the create files export configuration option
3) Test download with a single salesforce record that has a file attachment
4) Run "export files from org" option

The process returns the following on a chunk of parent records that have attachments... 

![image](https://user-images.githubusercontent.com/102315157/159966734-d447298c-5aa4-4b87-a7ef-35817e770932.png)

I have verified that I have all required dependencies, and am running on windows 10.

What steps should I take to troubleshoot this issue?

**Comment by nvuillam** [comment]
Please could you share your export.json ?

**Comment by michael-uls33** [comment]
See the attached export.json saved as text.

I added the limit because I was using more API requests than I felt comfortable testing. In one of my tests I selected a single record that had an attached file.

Thank you
[export.txt](https://github.com/hardisgroupcom/sfdx-hardis/files/8343855/export.txt)

**Comment by nvuillam** [comment]
You have 15000 bulk api calls by day, you can remove the limit, and at worse hit CTRL+C if you want to stop the process before the end :)

Here your 500 records just do not have attached files :/

**Comment by nvuillam** [comment]
No news, good news ? :)
Please reopen the issue if you still have the issue after removing the LIMIT, and we'll see how we can solve it :)

**Comment by michael-uls33** [comment]
Hi, thanks again for the reply. That solution didn't work using the hardis tool. Since then, I pursued a python solution which is working.

**Comment by nvuillam** [comment]
sfdx-hardis command is working , I'm pretty convinced that somewhere in your local files you had a json file with an error in it :/

I'm glad you found another way anyway :)
