### ISSUE TITLE
Unexpected token in JSON at position 210

### ISSUE THREAD

**Issue by sharad272** [hardisgroupcom/sfdx-hardis#220]
Hi,

I am facing this error while  "export files from org" option

<img width="352" alt="image" src="https://user-images.githubusercontent.com/63502537/161578915-47926e76-ecbe-423c-859b-3c34e8335546.png">

This is my export.json file

{
  "sfdxHardisLabel": "attach",
  "sfdxHardisDescription": "all attchments",
  "soqlQuery": "SELECT Id,Name FROM Opportunity",
  "fileTypes": "all",
  "outputFolderNameField": "Name",
  "overwriteParentRecords": true,
  "overwriteFiles": true
}

Any help would be much appreciated!

**Comment by nvuillam** [comment]
@sharad272 please can you run the following and post the result here ?

`sfdx plugins`

Example result:
```
$ sfdx plugins
@salesforce/sfdx-scanner 2.12.0
bbdoc 4.0.5
sfdmu 4.12.11
sfdx-essentials 2.12.0
sfdx-git-delta 5.0.6
sfdx-hardis 2.74.2
sfpowerkit 4.1.5
source 1.0.16
texei-sfdx-plugin 1.14.4
```

**Comment by sharad272** [comment]
> 



> @sharad272 please can you run the following and post the result here ?
> 
> * `sfdx plugins`
> 
> Example result:
> 
> ```
> $ sfdx plugins
> @salesforce/sfdx-scanner 2.12.0
> bbdoc 4.0.5
> sfdmu 4.12.11
> sfdx-essentials 2.12.0
> sfdx-git-delta 5.0.6
> sfdx-hardis 2.74.2
> sfpowerkit 4.1.5
> source 1.0.16
> texei-sfdx-plugin 1.14.4
> ```
> 
> * `node --version` result may help too
> * the full log, or at least a bigger part (you can anonymize your client info) would also help :)

These are my sfdx plugins

`
<img width="176" alt="image" src="https://user-images.githubusercontent.com/63502537/161696989-41325fa8-eee6-46bd-aa58-f268f2056adf.png">
`
 
Also in dependency section I have

`
<img width="187" alt="image" src="https://user-images.githubusercontent.com/63502537/161697150-eb2301b2-bb1d-4e39-ac68-25ca984e1fa5.png">
`

Is the error I am facing because of these missing dependencies I have above?

**Comment by nvuillam** [comment]
You are using a local version of sfdx-hardis (and other plugins), please try you try again after being up to date with dependencies ?

And if it still fails, please can you share a bigger part of the console log ?

**Comment by sharad272** [comment]
I have updated the missing dependencies still getting this error.

<img width="178" alt="image" src="https://user-images.githubusercontent.com/63502537/161922544-9dcbb34e-eeab-4d00-ae7d-3decf6c27b44.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/63502537/161922913-e796c3fe-bfe8-47eb-b03d-c34119eab957.png">

**Comment by nvuillam** [comment]
Could you please run the command with `--dev-debug` at the end and share the log ?

**Comment by sharad272** [comment]
Hi Nvuillam, 

Sorry for replying to this late, Actually this issue got resolved when I reconfigured the plugin with my friend's help. Thanks for you help.

**Comment by nvuillam** [comment]
@sharad272 i'm glad the problem is solved :)
May I know how, just in case someone else has the same issue ?
