### ISSUE TITLE
legacy api result shows wrong area

### ISSUE THREAD

**Issue by wolffsblut69** [hardisgroupcom/sfdx-hardis#225]
Hi, 
thanks for this great scanner feature. works really fine, but very small issue found:
log entries is shown in wrong category. in my scan entries from 21-30 are shown in the 7-20 category
![image](https://user-images.githubusercontent.com/62156414/162195012-64a901df-b115-49c6-979f-d7f9f6439cf6.png)
in CSV file:
![image](https://user-images.githubusercontent.com/62156414/162195340-b30d4f3e-cdfd-4b76-a8f1-0ea56dee5d92.png)

cheers
Markus

**Comment by nvuillam** [comment]
@wolffsblut69 there is indeed a bug in either of the console or CSV, I'll check, thanks for catching the issue :)

**Comment by nvuillam** [comment]
@wolffsblut69 it should be all good now with latest version (2.78.2) , please can you confirm it's ok on your side too ? :)

Note: now default output files are in CWD+ ./hardis-report folder :)
