### ISSUE TITLE
ERROR running hardis:project:generate:gitdelta

### ISSUE THREAD

**Issue by deckblad** [hardisgroupcom/sfdx-hardis#230]
I'm attempting to use the gitdelta package generation script and am getting the following output error. I'm running latest version v2.78.2. This problem had just started recently. In this example I'm comparing between two adjacent commits on the same branch.

`[sfdx-hardis] {"value":{"hash":"f9________________________________a8bdd3","date":"2022-04-07T16:35:57-05:00","message":"I diiiid it","refs":"HEAD -> CRM-934-TaskPermission, origin/CRM-934-TaskPermission","body":"","author_name":"________","author_email":"____________@gmail.com"}}
[sfdx-hardis][command] git rev-parse --show-toplevel
✖ [sfdx-hardis][command] sfdx sgd:source:delta --from 3c00bea7132cd4d2ac0d13f55ab9c63b78fc7fe2 --to f98f5e0fafff068b998a76ee4fd1e09f3ea8bdd3 --output C:\Users\______\AppData\Local\Temp\sfdx-hardis-vuz2m`

    TypeError: Cannot read properties of undefined (reading 'prototype')

`ERROR running hardis:project:generate:gitdelta:  Command failed: sfdx sgd:source:delta --from 3c00bea7132cd4d2ac0d13f55ab9c63b78fc7fe2 --to f98f5e0fafff068b998a76ee4fd1e09f3ea8bdd3 --output C:\Users\______\AppData\Local\Temp\sfdx-hardis-vuz2m`

    TypeError: Cannot read properties of undefined (reading 'prototype')

**Comment by nvuillam** [comment]
Please can you share the sfdx git delta command run by sfdx-hardis ?

**Comment by nvuillam** [comment]
@deckblad please can you share the output of `sfdx plugins` ?

**Comment by deckblad** [comment]
$ sfdx -v
sfdx-cli/7.147.1 win32-x64 node-v16.14.2

$ sfdx plugins
sfdmu 4.13.4
sfdx-essentials 2.12.0   
sfdx-git-delta 5.2.0     
sfdx-hardis 2.85.1       
sfpowerkit 4.2.5
shane-sfdx-plugins 4.43.0
├─ @mshanemc/plugin-streaming 1.1.7
└─ @mshanemc/sfdx-sosl 1.1.0       
texei-sfdx-plugin 1.14.4

$ node --version
v16.15.0

**Comment by nvuillam** [comment]
I don't understand, I have a similar configuration and it works well :/

```shell
node v16.14.2
sfdx-cli/7.147.1 win32-x64 node-v16.14.2
sfdmu 4.13.4
sfdx-essentials 2.12.0
sfdx-git-delta 5.2.0
sfdx-hardis 2.85.1
sfpowerkit 4.2.5
texei-sfdx-plugin 1.14.4
```

![image](https://user-images.githubusercontent.com/17500430/165641087-3e645e7e-6314-42ef-aa39-16873cc232a9.png)

If it's crashing within sfdx git:delta, it may be related to sfdx-git-delta plugin... @scolladon @mehdisfdc maybe you already saw such error ?

@deckblad please could you share the full (anonymzed) log ?

**Comment by mehdisfdc** [comment]
Yes maybe it's related to [sfdx-git-delta](https://github.com/scolladon/sfdx-git-delta).
@deckblad can you run the `sfdx sgd:source:delta` command directly to see you get an error or unexpected outpout?

According to the log you shared, the sfdx-hardis plugin tried to execute `sfdx sgd:source:delta --from 3c00bea7132cd4d2ac0d13f55ab9c63b78fc7fe2 --to f98f5e0fafff068b998a76ee4fd1e09f3ea8bdd3 --output C:\Users\______\AppData\Local\Temp\sfdx-hardis-vuz2m`

Could you please run it directly and share the result (and verify that the output folder contains the expected files)?
Thank you!

**Comment by scolladon** [comment]
@deckblad before raising an issue on `sgd` side, could you retry with a fresh `sgd` reinstallation first (uninstall `sgd` and reinstall it) ?

**Comment by deckblad** [comment]
Ope, that did it. Despite my having every dependency up to date... odd Closing this one out!

**Comment by nvuillam** [comment]
I'm glad to know it works well for you now :)
Thanks @mehdisfdc and @scolladon for the assistance:)
