### ISSUE TITLE
Bug : Unfreeze users, the bulk data load update job is still in progress

### ISSUE THREAD

**Issue by mickaelgudin** [hardisgroupcom/sfdx-hardis#253]
The update of the object UserLogin doesn't appear to be working properly,
The Bulk Data Load Job of the update to unfreeze users is still in progress in the setup, and the changes are not commited until the job status is closed.

The bug occured both on sandbox and production environnements.
![image](https://user-images.githubusercontent.com/39730173/166683299-ba0fc148-962e-44a2-83f8-e991549c29ff.png)

**Comment by nvuillam** [comment]
Solved :)
