### ISSUE TITLE
node.exe is not recognized as an internal or external command

### ISSUE THREAD

**Issue by deckblad** [hardisgroupcom/sfdx-hardis#276]
I'm getting the following results when trying to run the package.xml git delta command. I've made sure all extensions and sfdx and plugins are up to date. This started happening a couple weeks ago.

`mrBlaQ@MEAT MINGW64 /d/Dev/VSCode/Salesforce (SandboxOnboardPI3)
$ sfdx hardis:project:generate:gitdelta --websocket localhost:2735
[sfdx-hardis] 🦙 Please select a Git branch  ↑↑ Look up in VsCode ↑↑
[sfdx-hardis] {"value":"SandboxOnboardPI3"}
[sfdx-hardis][command] git checkout SandboxOnboardPI3
[sfdx-hardis][command] git pull
[sfdx-hardis][command] git log --pretty=format:òòòòòò %H ò %aI ò %s ò %D ò %b ò %aN ò %aE òò --first-parent
[sfdx-hardis] 🦙 Please select the commit that you want to start from  ↑↑ Look up in VsCode ↑↑
[sfdx-hardis] {"value":{"hash":"48f03a1f9a66a55e843ffd9dc11a3b78ff5f7227","date":"2022-08-15T13:38:54-05:00","message":"Deploying upstream changes to onboardingpi3","refs":"","body":"","author_name":"#####","author_email":"#########"}}[sfdx-hardis] 🦙 Please select the commit hash that you want to go to  ↑↑ Look up in VsCode ↑↑
[sfdx-hardis] {"value":{"hash":"bee3e6e0565a27a0327cbfaaf4f1774042a9bfae","date":"2022-09-01T14:14:50-05:00","message":"Merge remote-tracking branch 'origin/main' into SandboxOnboardPI3","refs":"HEAD -> SandboxOnboardPI3, origin/SandboxOnboardPI3","body":"","author_name":"######","author_email":"#######"}}
[sfdx-hardis][command] git rev-parse --show-toplevel
✖ [sfdx-hardis][command] sfdx sgd:source:delta --from 48f03a1f9a66a55e843ffd9dc11a3b78ff5f7227 --to bee3e6e0565a27a0327cbfaaf4f1774042a9bfae --output C:\Users\mrBlaQ\AppData\Local\Temp\sfdx-hardis-zs2pr

'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.

ERROR running hardis:project:generate:gitdelta:  Command failed: sfdx sgd:source:delta --from 48f03a1f9a66a55e843ffd9dc11a3b78ff5f7227 --to bee3e6e0565a27a0327cbfaaf4f1774042a9bfae --output C:\Users\mrBlaQ\AppData\Local\Temp\sfdx-hardis-zs2pr
'"C:\Program Files\Salesforce CLI\bin\node.exe"' is not recognized as an internal or external command,
operable program or batch file.

[sfdx-hardis] hardis:project:generate:gitdelta execution time 0:00:13.120

mrBlaQ@MEAT MINGW64 /d/Dev/VSCode/Salesforce (SandboxOnboardPI3)
$ node
Welcome to Node.js v16.15.0.
Type ".help" for more information.
>
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
>`

**Comment by deckblad** [comment]
What's odd is if I run the SGD command manually in terminal, it works?

`$ sfdx sgd:source:delta --from 48f03a1f9a66a55e843ffd9dc11a3b78ff5f7227 --to bee3e6e0565a27a0327cbfaaf4f1774042a9bfae --output .
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": []
}`

This output creates the three expected files in the root of my project. Is there some different context sgd is running within when initiated from hardis?

**Comment by nvuillam** [comment]
I think you installed sfdx using the Salesforce installer, who embeds some version of node.js

- Go to Windows -> Programs -> Uninstall sfdx
- Install sfdx from npm using `npm install sfdx-cli -g`

That should work better :)

**Comment by deckblad** [comment]
Thanks! That worked!

I'll note that it's called "Salesforce CLI" in the Programs list.

**Comment by nvuillam** [comment]
Glad it worked :)

Have fun with sfdx-hardis :)
