### ISSUE TITLE
hardis:org:purge:flow is failing when selecting "All" option

### ISSUE THREAD

**Issue by micha79x** [hardisgroupcom/sfdx-hardis#297]
### Description

The `hardis:org:purge:flow` command starting in 2.83.0 is introducing the option to select among a list of all Flows in an Org or only a specific one.

When selecting the "All flows" option, the plugin is generating a Tooling API Query with the following SOQL:

```
SELECT Id,MasterLabel,VersionNumber,Status,Description FROM Flow WHERE Status IN ('Inactive') AND MasterLabel LIKE 'all%' ORDER BY MasterLabel,VersionNumber"
```

However, the filter for `MasterLabel LIKE 'all%'` is failing in 99% of all circumstances. ;) So as the Query is not returning any result the plugin just ends here.

I just downgraded to 2.92.2 and the old version of the command works just fine.

### Steps to reproduce

1. Install Hardis SFDX Plugin in Version 2.98.0
1. Run `sfdx hardis:org:purge:flow -u ALIAS` in an Org with at least 1 inactive Flow Version
    ![image](https://user-images.githubusercontent.com/45310/214095182-3baafc89-a5d4-4f40-91f4-89984ad8a648.png)
  
### Expected behaviour

After selecting "All flows" and all of the non-active Status, the Plugin should start deleting the Versions.

### Actual behaviour

No Flow Versions are found, and nothing gets deleted.

**Comment by nvuillam** [comment]
@micha79x thanks for reporting :)

It should be fixed by https://github.com/hardisgroupcom/sfdx-hardis/pull/298

Please can you confirm it's now ok with version 2.98.1 ?

**Comment by micha79x** [comment]
@nvuillam Confirmed, working as expected now, Thanks for fixing this so quickly. And thanks for the plugin overall. 👍
