### ISSUE TITLE
Lack of documentation for `metadataDuplicateFindKeys` property

### ISSUE THREAD

**Issue by przemekrcloudity** [hardisgroupcom/sfdx-hardis#339]
Hi! I think that documentation for `metadataDuplicateFindKeys` property is missing.

Today I installed your pluign and tried to test duplicate metadata detection logic.
I created duplicate label in `force-app/main/default/labels/CustomLabels.labels-meta.xmll` file and after running
```sh
sfdx hardis:project:metadata:findduplicates
```
I got:
```
[sfdx-hardis] Start finding duplicate values in XML metadata files.
[sfdx-hardis] Done finding duplicate values in XML metadata files.
[sfdx-hardis] hardis:project:metadata:findduplicates execution time 0:00:00.375
```
When I tried to run the same command with `--help` flag, help page mentioned that I need to specify which files I want to check using `metadataDuplicateFindKeys.` property in config file but there is no mention of this property in [config documentation](https://sfdx-hardis.cloudity.com/schema/sfdx-hardis-json-schema-parameters.html).

**Comment by nvuillam** [comment]
@clemfernandez any thoughts to reply to @przemekrcloudity ? :)

**Comment by clemfernandez** [comment]
@przemekrcloudity you're right the property wasn't well documented.

I just created a PR to fix that, in the meantime you can use it like so : 
```json
{
  "metadataDuplicateFindKeys": {
    "layout": [
      "Layout.layoutSections.layoutColumns.layoutItems.field",
      "Layout.quickActionListItems.quickActionName"
    ],
    "profile": [
      "Profile.fieldPermissions.field"
    ]
  }
}
```

**Comment by nvuillam** [comment]
@przemekrcloudity if you detect other checks that could be added by default, don't hesitate to add a PR to update here -> https://github.com/hardisgroupcom/sfdx-hardis/blob/138d0024df0ebe455a0c733a248fe47382071215/src/commands/hardis/project/metadata/findduplicates.ts#L24 :)
