### ISSUE TITLE
Lack of colors in logs in terminals supporting only ANSI colors

### ISSUE THREAD

**Issue by przemekrcloudity** [hardisgroupcom/sfdx-hardis#345]
I don't know if it is in the scope of this plugin or package used for logging, but I have noticed that colorful logs aren't properly displayed in bitbucket (which supports only ANSI colors). 

![image showing lack of colors in bitbucket console](https://user-images.githubusercontent.com/95613238/229065836-3518cfba-8bdd-4c8e-98f3-fc2b9077bc01.png)

Would it be possible to add support for ANSI colors to logs or at least detect when the plugin is running in bitbucket (this can be achieved by [checking env variables](https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/))  and then use this coloring mechanism instead of the one used by chalk? 

Working  implementation of such color scheme can be [found here](https://github.com/Ziemniakoss/sfdx-ci-summary-creator/blob/master/src/utils/colorStrings.ts).

**Comment by nvuillam** [comment]
Please can you try to define env variable ``FORCE_COLOR: "1"` ?

Gitlab CI had the same issues, and with such variable chalk always displays colors :)

**Comment by przemekrcloudity** [comment]
Thanks, it worked
