### ISSUE TITLE
New Hint suggestion

### ISSUE THREAD

**Issue by przemekrcloudity** [hardisgroupcom/sfdx-hardis#352]
When user breaks xml by adding text before XML definition header, like:
```xml
some_text_that_I_accidentally_pasterd<?xml version="1.0"
    encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <applicationVisibilities>
```
SFDX returns error:
```
Error parsing file: Content is not allowed in prolog. (1:1)
```
I think it would be helpful to detect such issue and instruct user that they probably added some text in first line of XML

**Comment by nvuillam** [comment]
Indeed that's a great idea :)

Please can you share the full block of text returned by the sfdx command ?

**Comment by przemekrcloudity** [comment]
I'm sorry, but I can only share this part of the deployment report
```
=== Component Failures [1]

 Type  Name  Problem                                                     
 ───── ───── ─────────────────────────────────────────────────────────── 
 Error Admin Error parsing file: Content is not allowed in prolog. (1:1) 
```
But the XML I provided (after adding closing tags) should be enough to reproduce this deployment issue

**Comment by nvuillam** [comment]
That's enough, it will allow to create the regex to show that the issue comes from **Admin** and create the error message using it :)

Would you like to make the PR ?

https://github.com/hardisgroupcom/sfdx-hardis/blob/main/src/common/utils/deployTipsList.ts

The block to create is very similar to this one :)

```javascript
    {
      name: "can-not-change-to-formula-field",
      label: "Can not change field type to a formula field",
      expressionRegex: [/Error (.*) Cannot update a field from a Formula to something else/gm],
      tip: `You need to manually delete or rename the field in the target org to allow the deployment to pass
- First, try to manually delete field {1} in the target org
- if you can't delete {1}, rename it into {1}_ToDel, then once the deployment done, delete {1}_ToDel`,
    },
```

**Comment by przemekrcloudity** [comment]
I would love to create PR but currently, I don't have enough time to allocate to develop this project.

**Comment by nvuillam** [comment]
No problem I'll take the 10 mn and credit you as co-author, as you notified of the issue :)
