### ISSUE TITLE
[Deployment wrapper] Don't color output of deployment command

### ISSUE THREAD

**Issue by przemekrcloudity** [hardisgroupcom/sfdx-hardis#355]
By coloring the result of wrapped deployment command (to grey when it was successful and to red when it failed), coloring of output of [sfdx-ci-summary-creator](https://github.com/Ziemniakoss/sfdx-ci-summary-creator) is broken. 
Could it be possible not to color output of `sfdx force:source:deploy` command? 
We really need this plugin because it generates:
- JUnit report for deployment
- outputs time of unit test (this way we know on what unit tests to focus to reduce build time)
- warnings about coverage
- command output that makes it easier to pinpoint issues with deployment

**Comment by przemekrcloudity** [comment]
Hi, sorry for delay. What I meant is that:
- colors in output are very useful and I want to keep them
- colorful output from linked plugin is overwritten by red color of error logs.

Error with no `sfdx-hardis` plugin:

![ci_summary_report](https://github.com/hardisgroupcom/sfdx-hardis/assets/95613238/0c7aa265-b6b3-4be2-9b54-874ddce55a8e)

Error with `sfdx-hardis` plugin
![ci_summary_report_in_hardis](https://github.com/hardisgroupcom/sfdx-hardis/assets/95613238/f395a922-9abc-4a44-b25b-ddb57f7c20a9)

(same happens with failed unit tests)

Could be possible to disable coloring of only printed out deployment result?

**Comment by nvuillam** [comment]
oh ok I understand :)

Do you call sfdx-hardis within your plugin ? if so, how ?

I could add a ENV variable that will disable the red coloring with chalk, I just need to understand where :)

**Comment by przemekrcloudity** [comment]
This plugin is called by SFDX after deployment using build-in hooks and its output is appended to `sfdx force:source:deploy` conmmand's output. 
Reproduction steps for my issue:
1. make sure both sfdx-hardis and sfdx-ci-summary-creator (minimal version 4.2.0 as it introduces stdio output) plugins are installed
2. run deployment using `sfdx hardis:source:deploy`
3. See that output of sfdx-ci-summary-creator command changed colors

**Comment by nvuillam** [comment]
@przemekrcloudity you have a look at latest version, it should fit your requirement :)

https://github.com/hardisgroupcom/sfdx-hardis/releases/tag/v3.19.3

**Comment by przemekrcloudity** [comment]
Thanks! Works great
