### ISSUE TITLE
Unable to export files relating to Cases

### ISSUE THREAD

**Issue by will-jansen** [hardisgroupcom/sfdx-hardis#357]
We are unable to export Files relating to Cases, the script appears to hang at Bulk query.

We have tried: 
- with and without WHERE clauses in the query
- production and sandbox instances
- different orgs.

We can export Files related to Accounts, Contacts and custom objects.
The dependencies appear all up to date.

<img width="297" alt="Screenshot 2023-04-12 at 12 30 16 pm" src="https://user-images.githubusercontent.com/73018431/231337201-52f8295a-a0f7-48d2-a858-beeba56d7e91.png">
<img width="1155" alt="Screenshot 2023-04-12 at 12 27 28 pm" src="https://user-images.githubusercontent.com/73018431/231337208-dac3c5c0-6daf-4e4d-9170-30b71c458525.png">

**Comment by nvuillam** [comment]
The "in 0 chunks" could be a clue...
Maybe some bug in sfdx-hardis that would skip the first chunk :/

Do you have typescript expertise ?

It needs to be debugged

**Comment by nvuillam** [comment]
Instructions to debug locally are here -> https://sfdx-hardis.cloudity.com/#contributing

**Comment by nvuillam** [comment]
Meanwhile just to diagnose, could you try the command with option `--chunksize 3` ?

**Comment by will-jansen** [comment]
Thank you for getting back to me. I do not have typescript expertise but may be able to hand this off to another member in my team.

How can i add --chunksize 3 to the commend?

**Comment by will-jansen** [comment]
Hi again, changing the chunksize to 3 and update the startnumber does not make any difference. 

I'm still working on the typescript logs

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/73018431/231632027-01e25b38-8c93-4e39-8a32-92cc98af2de1.png">

**Comment by nvuillam** [comment]
Ok, so basically everytime the bulk api request is started on Case, it hangs forever and you need to kill the command ?

**Comment by will-jansen** [comment]
Yeah that’s correct.

**Comment by nvuillam** [comment]
![image](https://user-images.githubusercontent.com/17500430/232232529-686d4694-bd9e-4dd9-9e5c-4c0a03f34201.png)

Please can you check if you see a job on Case in Setup -> Bulk data load jobs  ?

**Comment by will-jansen** [comment]
🤦🏻‍♂️
@nvuillam, I had Name in the Case query. Their is no Name field in Case... Sorry about that. Thanks for jumping on this quickly and pointing me in the right direction. The export is working fine now without Name in the query.

**Comment by nvuillam** [comment]
@will-jansen no problem, it happens, especially when you have a client pressuring you gor immediate results 😅

I'm glad your issue is solved :)
