### ISSUE TITLE
"API version not found or not supported, using '57' instead"

### ISSUE THREAD

**Issue by rishabh2095s** [hardisgroupcom/sfdx-hardis#378]
I get this error when I put 58 in json file. Plus I cant override it by api tag because we are using sfdx command not sf

**Comment by nvuillam** [comment]
What sfdx-hardis command are you trying to run ?

Please can you detail ?

It seems that you are trying to deploy with v58 (Summer '23) in an org that is on v57 (Spring' 23)

**Comment by rishabh2095s** [comment]
the environment I am trying to deploy is on 58 version but still when I change the json file it throws the above error. And I can't put the old -a,--apiversion tag as it has been changed to --api-version because of the new sf commands.

**Comment by rishabh2095s** [comment]
I am using sgd command to create the delta but using hardis docker image, and using normal sfdx command to deploy it the delta package.

**Comment by rishabh2095s** [comment]
tried using hardis deploy command too, im getting the same result

**Comment by nvuillam** [comment]
If you use the new version commands, they may still have some issues :/

You probably should change the apiVersion in the XML metadatas to go back in v57

**Comment by rishabh2095s** [comment]
I did change the api version XML file but the only workaround I found was to remove the new tags introduced in flow in v58. Thanks, anyways.
