### ISSUE TITLE
Add plugin new command sf

### ISSUE THREAD

**Issue by lramosmtx** [hardisgroupcom/sfdx-hardis#384]
Hi @nvuillam ,

I think it should be great to move the commandline sfdx to sf. The sfdx will be deprecated.

Cheers,
Lionel

**Comment by nvuillam** [comment]
hi @lramosmtx , thanks for your interest in sfdx-hardis :)

As [explained by sf cli team](https://github.com/forcedotcom/cli/issues/2132) , a sf plugin v2 will be released, and will make sfdx commands still available :)

It is currently still in beta and I don't want sfdx-hardis users to be beta-testers, but once it will work GA I will switch the dependency from sfdx to sf (while still calling sfdx commands ^^ )

**Comment by leojok-fluido** [comment]
@nvuillam : Seems that 12.7 it happened, "sf (v2) became generally available on July 12, 2023. At that time we stopped publishing updates to sfdx (v7) and sf (v1). To get new Salesforce CLI features and bug fixes, you must use sf (v2)."

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm

**Comment by nvuillam** [comment]
@leojok-fluido the PR is ready, but as i'm in vacation i prefer to wait being back to merge it, to avoid risking regressions ^^

https://github.com/hardisgroupcom/vscode-sfdx-hardis/pull/108

Meanwhile i'm pretty sure everything will keep going well with sfdx-cli :)

**Comment by nvuillam** [comment]
@lramosmtx @leojok-fluido that's ok now :)

--> https://github.com/hardisgroupcom/sfdx-hardis/releases/tag/v4.0.1

**Comment by lramosmtx** [comment]
Fantastique!


Lionel Ramos

Engineering Manager - Salesforce

***@***.*** | +33 670 871 672

36 rue de Saint-Pétersbourg, 75008 Paris

www.meilleurtaux.com<http://www.meilleurtaux.com/>

________________________________
De : Nicolas Vuillamy ***@***.***>
Envoyé : dimanche 20 août 2023 22:11
À : hardisgroupcom/sfdx-hardis ***@***.***>
Cc : RAMOS Lionel ***@***.***>; Mention ***@***.***>
Objet : Re: [hardisgroupcom/sfdx-hardis] Add plugin new command sf (Issue #384)


@lramosmtx<https://github.com/lramosmtx> @leojok-fluido<https://github.com/leojok-fluido> that's ok now :)

--> https://github.com/hardisgroupcom/sfdx-hardis/releases/tag/v4.0.1
