### ISSUE TITLE
Unable to use plugin on MAC M1 

### ISSUE THREAD

**Issue by idanblich** [hardisgroupcom/sfdx-hardis#391]
All plugin commands return : 
```TypeError: Cannot read properties of undefined (reading 'prototype')```

vs. ```sfdx force:org:open``` from vs sidebar (hardis extention) works as expected 

sfdx -v 
```sfdx-cli/7.209.6 darwin-arm64 node-v20.5.0```
sfdx plugins
```@salesforce/sfdx-scanner 3.13.0
dev 0.7.13 (0.7.13)
sfdmu 4.29.5
sfdx-essentials 2.12.0
sfdx-git-delta 5.24.1
sfdx-hardis 3.19.4
sobject 0.1.32 (0.1.7)
texei-sfdx-plugin 1.17.3
```

same installation on MAC intel - works as expected

**Comment by nvuillam** [comment]
I don't know plugins dev and sobject, they might have a craqh in a pre or post command hook

Please can you run the same command with --dev-debug and share the output here ?

**Comment by idanblich** [comment]
> I don't know plugins dev and sobject, they might have a crash in a pre or post command hook

This work !  i removed this plugins (by salesforce) and the hardis is not working 
TY 

Docker on M1 need to get new issue 🙀

**Comment by nvuillam** [comment]
Docker on M1 has many issues.... :) ( I see that with my MegaLinter project )

Quick question: why do you try to run sfdx-hardis with docker locally ?
Why not just installing it ? :)

**Comment by leojok-fluido** [comment]
@nvuillam : Just played around upgrading from sfdx to sf locally and wanted to test hardis docker image build to see that does it work in docker M1 combo ;)

**Comment by nvuillam** [comment]
@leojok-fluido if nothing in [this dockerfile(https://github.com/hardisgroupcom/sfdx-hardis/blob/main/Dockerfile) I can also build & publish for other platforms in a future release :)

**Comment by nvuillam** [comment]
@leojok-fluido @idanblich it seems that it will be more complicated than what I thought... :D 

I use the docker-build-push official Github Action and... it seems that either with sfdx-cli or @salesforce/cli , arm64 & arm/v7 , qemu doesn't seem to emulate well enough to make the sfdx plugins install :/ 

https://github.com/hardisgroupcom/sfdx-hardis/actions/runs/5731956350/job/15533964039?pr=392

**Comment by nvuillam** [comment]
@idanblich it's fixed in latest version :)
