### ISSUE TITLE
Bulkify flow deletions

### ISSUE THREAD

**Issue by przemekrcloudity** [hardisgroupcom/sfdx-hardis#416]
Today I used this plugin to delete obsolete flows and I had over 150 flow versions to delete and it took around 10 minutes to execute (still a LOT faster than manually deleting flows). 
If I understand correctly, command for flow deletions calls `sfdx` to delete flow versions using tooling API.
Is there a way to bulkify this process? Tooling API supports [bulk deletions](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_resources_composite_sobjects_collections_delete.htm) (but to be fair I haven't used it for flow deletions so I can't guarantee it will work in this application). If this doesn't work maybe using [composite API](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_requests_composite_composite.htm) woudl be good idea?

**Comment by nvuillam** [comment]
When I created the command I tried to but didn't succeed

I think we need to create a CSV then call the tooling bulk API, would you like to make a PR  ? :)

**Comment by przemekrcloudity** [comment]
@nvuillam I am sorry but due to my responsibilities, I don't have any free time :(, I am just sharing ideas for improvement

**Comment by nvuillam** [comment]
Solved by @masaner :) https://github.com/hardisgroupcom/sfdx-hardis/releases/tag/v4.37.5
