### ISSUE TITLE
Automated installation of all dependeces is not working after fresh install.

### ISSUE THREAD

**Issue by PawelWozniak** [hardisgroupcom/sfdx-hardis#417]
Just installed this plugin in VSCode. I see on Dpendeces all on red and got a message to upgrade all of them. 
Clicked Upgrade button.

In Terminal (git bash) it runs then:

`$ echo y|sfdx plugins:install sfdx-git-delta && echo y|sfdx plugins:install @salesforce/plugin-packaging && echo y|sfdx plugins:install texei-sfdx-plugin && echo y|sfdx plugins:install sfdmu && echo y|sfdx plugins:install sfdx-hardis && sfdx hardis:work:ws --event refreshPlugins --websocket localhost:2778
? This plugin is not digitally signed and its authenticity cannot be verified. Continue installation? Yes
Because you approved this plugin, you can avoid future installation confirmations by adding the plugin to the unsignedPluginAllowList.json file. For details, see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_allowlist.htm.
Finished digital signature check.
Installing plugin sfdx-git-delta... \ [1/4] Resolving packages...
Installing plugin sfdx-git-delta... \ [2/4] Fetching packages...
warning "sfdx-git-delta > @salesforce/command > @oclif/test > @oclif/core > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
Installing plugin sfdx-git-delta... installed v5.25.2`

and return to the command line just after installing one plugin. Also plugins list is not refreshed in VSCode.
It seems that only the first command is executed and the rest is ignored.

When I refresh manually Dpendeces in VSC then upgrade option is again proposed, I agree and it runs:
`$ echo y|sfdx plugins:install @salesforce/plugin-packaging && echo y|sfdx plugins:install sfdmu && echo y|sfdx plugins:install texei-sfdx-plugin && echo y|sfdx plugins:install sfdx-hardis && sfdx hardis:work:ws --event refreshPlugins --websocket localhost:2778
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/plugin-packaging.
Finished digital signature check.
Installing plugin packaging... | [2/4] Fetching packages...
warning "sfdx-git-delta > @salesforce/command > @oclif/test > @oclif/core > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
Installing plugin packaging... installed v1.24.0`
and returns to the command line. 

I repeated that until all dependencies were installed

Windows 11
@salesforce/cli/2.7.11 win32-x64 node-v18.15.0
VSCode 1.18.1
SFDX Hardis by Cloudity v2.1.0

**Comment by nvuillam** [comment]
@PawelWozniak do you have a sfdx or Salesforce CLI that you installed with the Windows installer ?

If yes, you need to uninstall it ( Windows -> Programs -> Uninstall )

Then @salesforce/cli and plugins installation via NPM with work :)

**Comment by nvuillam** [comment]
@PawelWozniak I updated the doc and added you as co-author to thank you for reporting the issue :)

**Comment by PawelWozniak** [comment]
@nvuillam Yes I have Windows Installer version. Since now I have everything installed I will not check it but I believe that npm install does the trick.
