### ISSUE TITLE
TypeError When Executing sfdx-hardis Commands

### ISSUE THREAD

**Issue by yamioliva** [hardisgroupcom/sfdx-hardis#436]
Hello 👋,

I've been encountering an error when trying to run any command from the sfdx-hardis plugin, and I hope you might be able to shed some light on this issue.

Description of the issue:

When executing all command:

<img width="311" alt="image" src="https://github.com/hardisgroupcom/sfdx-hardis/assets/38166991/b2d3c546-ca9e-412a-a1b9-1bdd375253f0">

I'd like to add that I've already tried uninstalling and reinstalling the plugin from scratch. Interestingly, it works when I uninstall sfdmu, but this causes other issues: I cannot relaunch Run debugger and I am unable to analyze the logs. Have you encountered this problem before? Do you have any insights on how I might resolve it?

**Comment by nvuillam** [comment]
@yamioliva After our call, do you confirm that the bug does not happen anymore ? :)

**Comment by iowillhoit** [comment]
Hey @nvuillam, I just wanted to make sure you saw my post about this over on the Salesforce CLI issue repo. https://github.com/forcedotcom/cli/issues/2508#issuecomment-1760274510

**Comment by nvuillam** [comment]
@iowillhoit saw it thanks, now waiting for the fix ^^
I again had to remove sfdmu from CI/CD pipelines to avoid such crash :(

**Comment by nvuillam** [comment]
Fixed :)
