### ISSUE TITLE
SFDX Hardis: Activate debug logs tracing

### ISSUE THREAD

**Issue by anthonygiuliano** [hardisgroupcom/sfdx-hardis#437]
Hi, I'm having some trouble activating debug log tracing across different orgs. When I run this from the command palette, the extension reports the following:

`🦙 Salesforce Extension pack command not found. If it is installed, just wait for it to be initialized :)`

I think it started happening last week, and it seems to happen consistently across different orgs, regardless of sandbox or prod. I can't find any other helpful logs anywhere, but maybe you can point me in the right direction.

As a workaround, I set my debug level using dev console and just leave the window open while I work.

SFDX
@salesforce/cli v2.11.8
@salesforce/plugin-packaging v1.26.3
sfdmu v4.30.0
sfdx-essentials v2.12.0
sfdx-git-delta v5.26.2
sfdx-hardis v4.6.4
texei-sfdx-plugin v2.1.2

Core
Node.js ~/.nvm/versions/node/v18.17.1/bin/node
Git

VsCode Extensions
Salesforce Extensions Pack

Visual Studio Code
Version: 1.83.0
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:13:10.518Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.0.0

**Comment by nvuillam** [comment]
@anthonygiuliano i'm about to publish an enhancement that will display more of the error message when calling the SF Core extension command

Since salesforce/cli, there have been multiple reports of issues while using the debugger, so at least we'll see which issue it is :)

**Comment by nvuillam** [comment]
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/17500430/d6493390-da95-428d-bbde-c5de658e0a93)

Got it, SF changed the name of their commands :D 

So I have to also change them in VsCode sfdx-hardis , stay tuned :)
