### ISSUE TITLE
Technical Error after a succesful deploy ( orgCoverage.toFixed is not a function)

### ISSUE THREAD

**Issue by laissaouibrahim** [hardisgroupcom/sfdx-hardis#445]
Hi,
I'm trying to configure Azure devOps pipelines using sfdx-hardis. After deployement succeed ( deploy + test class execution ) . I got this error : 
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/91ee3340-68ee-4425-a9aa-27665a51f26a)

Any idea ?
thanks

**Comment by nvuillam** [comment]
@laissaouibrahim there is probably a bug causes by some change in the format of output data returned by Salesforce core command

I'll check ^^

**Comment by laissaouibrahim** [comment]
Here is my api version infos :
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/28154d1e-5c90-4af4-8bcf-2f25dd638b57)

**Comment by nvuillam** [comment]
@laissaouibrahim please can you try with 4.6.6 ?

It probably won't solve the problem but at least not crash, and explain why it crashed in the logs :)

**Comment by laissaouibrahim** [comment]
@nvuillam  : I confirm that 4.6.6 version fix the issue. 
Here is the result : 
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/c483f391-1e7b-4911-bc53-15787336b69c)

Many thanks & i happy to use sfdx-hardis extention :)

**Comment by nvuillam** [comment]
@laissaouibrahim it does crash but it does not control the org coverage ... not so good haha ^^

I'll try to reproduce and solve it :)

**Comment by nvuillam** [comment]
@laissaouibrahim please can you share your pipeline yml ? :)

**Comment by nvuillam** [comment]
> @nvuillam : Here is the yaml file : [azure-pipelines-deployment.zip](https://github.com/hardisgroupcom/sfdx-hardis/files/13055879/azure-pipelines-deployment.zip)

Thanks
After looking at it, the problem is not from the pipeline

Must be in salesforce/cli, I'll check :)
