### ISSUE TITLE
Consider adding ContentVersion.Id to output filename in hardis:org:files:export

### ISSUE THREAD

**Issue by piotrekkr** [hardisgroupcom/sfdx-hardis#447]
When `hardis:org:files:export` is running it is using [`downloadContentVersionFile()`](https://github.com/hardisgroupcom/sfdx-hardis/blob/main/src/common/utils/filesUtils.ts#L237). This method is downloading and saving content version file using normalized value of `contentVersion.Title`. This is not ideal because there can be multiple uploaded version of a file with same `Title`. This method will override all previous versions when downloading.

It happened to me few times already when validating if all files versions were downloaded and are on disk. I had some differences in files count between SF query result and disk. I started to debug this issues and found that some booking in SF had multiple uploaded versions of files with same `Title` (but different sizes and checksums). Then I found about `downloadContentVersionFile()` method and how it works.

My proposition is to add a `ContentVersion.Id` to output file name so it will not override other versions and this command will actually download all file versions (as it suppose to imho).

Something like this:
```
let outputFile = path.join(parentRecordFolderForFiles, `${contentVersion.Id}_${contentVersion.Title.replace(/[/\\?%*:|"<>]/g, "-")}`);
```

I understand that will probably be a breaking change so it could be done for example by creating a new command like `hardis:org:files:export-all-versions` or something like this that would use version id in output file name.

Let me know what you think. Thanks.

**Comment by nvuillam** [comment]
@piotrekkrgood catch !
I think that for easier file browsing it would be better to have `${contentVersion.Title.replace(/[/\\?%*:|"<>]/g, "-")}_${contentVersion.Id}`

You can keep the same command but add a new parameter `filenameformat` that could take the following values:
- title-id
- title
- id

Would you like to make a Pull Request ? :)

**Comment by piotrekkr** [comment]
Not sure I will manage to do this PR because I don't know typescript or codebase that much. I'll try tho.

**Comment by piotrekkr** [comment]
@nvuillam I created a PR. Sorry for ugly code. I'm not js dev. I used `<id>` and `<title>` since just `id` or `title` could be specified as part of format string and not a real placeholder e.g. `--filenameformat=entitlement-id-title`. Seems more clear to use it like `--filenameformat=entitlement-<id>-<title>`. Let me know wdyt.

I had not yet tested this code. Not sure if I can do this easily with my current setup. I'll try when I have time.

**Comment by piotrekkr** [comment]
@nvuillam Looking at the [diff](https://github.com/hardisgroupcom/sfdx-hardis/commit/0dcfb78b6a9f5c8384bc95a99b2cf25e87fd2aef) I don't think this new option is on main. Maybe you mixed pr with this revert one?

**Comment by nvuillam** [comment]
@piotrekkr i removed the CLI option but replaced it by a property in export.json , as you'll probably always want to output the same filename format :)

**Comment by nvuillam** [comment]
you can test by upgrading sfdx-hardis `sfdx plugins:install sfdx-hardis` then 
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/17500430/d0d05175-4fec-4508-acd2-16d163462c24)
 in vscode sfdx-hardis :)

**Comment by nvuillam** [comment]
@piotrekkr Do you have a linked Profile that I can mention in the new feature announce ? :)

**Comment by piotrekkr** [comment]
@nvuillam Yeah sorry about that. I just now compared latest tag with previous and then I saw full picture. Thanks for releasing :tada:. 

Yeah I'm using this extension with docker image on VM so no vscode involved but I will test it tomorrow. Thanks

**Comment by nvuillam** [comment]
@piotrekkr thanks, please let me know your feedback :)

**Comment by piotrekkr** [comment]
> @piotrekkr Do you have a linked Profile that I can mention in the new feature announce ? :)

@nvuillam Sorry for silly question but what do you mean by linked profile? Like linked to what?

**Comment by nvuillam** [comment]
@piotrekkr i communicate about sfdx-hardis to improve its adoption, and I consider normal to mention the contributors that helped to improve it :)

(but it's totally optional if you don't want to ^^ )

**Comment by nvuillam** [comment]
Something like that ^^ https://www.linkedin.com/in/nicolas-vuillamy/

**Comment by piotrekkr** [comment]
I have linkedin: https://www.linkedin.com/in/piotr-kroczy%C5%84ski-7aa61b5b/
