### ISSUE TITLE
salesforce/cli v2.13.9 (WRONGLY INSTALLED) error

### ISSUE THREAD

**Issue by benji1304** [hardisgroupcom/sfdx-hardis#455]
I'm getting this error on Hardis dependencies, but everything is working.

Working on a mac

Not sure what to do?

**Comment by nvuillam** [comment]
@benji1304 it is indeed working, but salesforce/cli updates won't work as you installed it using Mac installer

Can you uninstall it then reinstall it with node.js using `npm install @salesforce/cli -g` ?

**Comment by benji1304** [comment]
Fixed! Thanks for your help :)

**Comment by nvuillam** [comment]
You're welcome:)

**Comment by benji1304** [comment]
hey @nvuillam 
i'm not sure how to fix this, an older project still shows the old version of `@salesforce/cli`

**Comment by benji1304** [comment]
sorted! It was because i'd downgraded my node version due to an issue, and didn't realise this would break!

**Comment by nvuillam** [comment]
I think node 18 is the minimum required :)

**Comment by benji1304** [comment]
I downgraded to Node 20 due to this issue
https://github.com/forcedotcom/cli/issues/2535
