### ISSUE TITLE
Azure DevOps : Pipeline Deployment Checks can't connect to SFDC ORG ( This command requires a username...)

### ISSUE THREAD

**Issue by laissaouibrahim** [hardisgroupcom/sfdx-hardis#456]
Hi ,
After configuring correctly variables + pipelines on Azure DevOps as mentionned on SFDXHardis docs. I have succesfully exectuted the deployment Job. But unfortunately the second job (deployment checks) failed because he can't retreive Org information from variables :

_ERROR running hardis:project:deploy:sources:dx:  This command requires a username. Specify it with the -u parameter or with the "sfdx config:set defaultusername=<username>" command._

Please Help ! 
thanks :)
Script : [azure-pipelines-checks.zip](https://github.com/hardisgroupcom/sfdx-hardis/files/13210177/azure-pipelines-checks.zip)

![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/778cb2b8-7cd3-4fe1-8422-504c13ecb546)

**Comment by nvuillam** [comment]
Did you configure the secret variables (SFDX_HARDIS_CLIENT_ID_XXXX, SFDX_HARDIS_CLIENT_KEYXXXX) also in the deployment pipeline in Azure config ?

**Comment by laissaouibrahim** [comment]
Yes all generated credentials are pushed + the secret variables are configured on each pipeline. This is confirmed with the success execution of the second Deployment Pipeline. I will Update sfdxHardis & generate again  CI config.
I will keep you informed :)

**Comment by nvuillam** [comment]
Please let me know :)

**Comment by laissaouibrahim** [comment]
Hi @nvuillam ,
After updating sfdxHardis + generating again credentials : problem solved. 
I think that i have make a mistake when changed my git branch name from develop**B**uild to developbuild .

**Comment by nvuillam** [comment]
@laissaouibrahim I'm glad your issue is solved :)
