### ISSUE TITLE
pre-deploy and post-deploy commands + context + runOnlyOnceByOrg

### ISSUE THREAD

**Issue by nvuillam** [hardisgroupcom/sfdx-hardis#466]
Allow to configure command lines to call before and after a deployment

**Comment by nvuillam** [comment]
Done :)

https://sfdx-hardis.cloudity.com/hardis/project/deploy/sources/dx/#deployment-pre-or-post-commands

**Comment by paferpo** [comment]
Is it possible to specify if the action is one time/recurring? It would useful to be able to specify that and storing the execution history in custom metadata/settings in each org to determined if it was already executed or not. Also a flag to don’t run them during PR validations.

**Comment by nvuillam** [comment]
@paferpo about one-time / recurring... as sfdx-hardis is stateless, I don't know where to store it :/

About the flag to run them only during deploy validation or effective deployments, I'm working on it with v5, you'll be able to use it soon :)

**Comment by paferpo** [comment]
Hi Nicolas, as I mentioned in my previous message, it can be stored in custom settings records of each org where you are deploying to and, with a simple query, you can check if the action id was already executed (check only when the action is one-time of course).

**Comment by nvuillam** [comment]
@paferpo I get it, it's just that it would require such custom setting / metadata to be existing before the deployment ^^
I'll see what I can do :)

**Comment by paferpo** [comment]
I can think of 2 options in case it helps: either create the custom setting object + the action record on the fly when it doesn't exist (checking using metadata.list/metadata.read or just a query that will fail when the object does not exist) or, if that's too much work, just show a message saying that to use that option, the custom setting with name x must exist before, when it's not found.

**Comment by nvuillam** [comment]
I don't like the principle to upload metadatas without the explicit acceptance from the user, so it will be option 2 :)
With a command to upload the metadata so users don't have to create it manually :)

**Comment by nvuillam** [comment]
@paferpo 

This is done in v5 (already tested and available using sf plugins install sfdx-hardis@alpha)

See documentation :)

https://github.com/hardisgroupcom/sfdx-hardis/blob/migrate-sf-plugin/docs/hardis/project/deploy/smart.md#deployment-pre-or-post-commands

**Comment by paferpo** [comment]
Awesome! I will give a try in my ci/cd setup :)

**Comment by nvuillam** [comment]
> Awesome! I will give a try in my ci/cd setup :)

Happy to help :)
If it works, don't hesitate to post about it 🥳

**Comment by paferpo** [comment]
Hi Nicolas, I played with it. It works very well :) 
As an improvement, it would be nice to have a folder e.g. "AutomatedActions" where you could have separate yaml files per action instead of having all defined in sfdx-hardis.yml, but not a biggie!

**Comment by nvuillam** [comment]
@paferpo actions can be branch-scoped so I prefer to let them in the branch-scoped .sfdx-hardis.yml file :)

**Comment by nvuillam** [comment]
@paferpo and please star the repository :) ( and post about it if it's your style ;) )
