### ISSUE TITLE
Plugin installation issues

### ISSUE THREAD

**Issue by TimPaulaskasDS** [hardisgroupcom/sfdx-hardis#487]
When I attempt to install the plugin, I'm getting errors. I have try rebuilding sqlite3 and removing my node_modules and package-lock.json files, and performing an npm install. However, the errors persist.

Installing plugin sfdx-hardis@latest... failed
 ›   Warning: sfdx-hardis > @oclif/config@1.18.17: Package no longer supported. Contact Support at 
 ›   https://www.npmjs.com/support for more info.
 ›   Warning: sfdx-hardis > @oclif/command@1.8.36: Package no longer supported. Contact Support at 
 ›   https://www.npmjs.com/support for more info.
 ›   Warning: sfdx-hardis > @oclif/errors@1.3.6: Package no longer supported. Contact Support at 
 ›   https://www.npmjs.com/support for more info.
 ›   Warning: sfdx-hardis > @gitbeaker/node@35.8.1: Please use its successor @gitbeaker/rest
 ›   Warning: sfdx-hardis > @salesforce/command@4.2.2: Package no longer supported. Contact Support at 
 ›   https://www.npmjs.com/support for more info.
 ›   Warning: sfdx-hardis > ms-teams-webhook@1.0.4: fix breaking change in ms-teams with version 2.0.0
 ›   Warning: sfdx-hardis > puppeteer@13.7.0: < 19.4.0 is no longer supported
 ›   Warning: sfdx-hardis > @salesforce/ts-sinon > sinon@5.1.1: 16.1.1
 ›   Warning: sfdx-hardis > markdown-toc > gray-matter > coffee-script@1.12.7: CoffeeScript on NPM has moved to 
 ›   "coffeescript" (no hyphen)
 ›   Warning: sfdx-hardis > @salesforce/ts-sinon > sinon > @sinonjs/formatio > samsam@1.3.0: This package has been 
 ›   deprecated in favour of @sinonjs/samsam
 ›   Warning: sfdx-hardis > markdown-toc > remarkable > autolinker > gulp-header@1.8.12: Removed event-stream from 
 ›   gulp-header
 ›   Warning: "@salesforce/sfdx-scanner > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
 ›   Warning: "sfpowerkit > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
 ›   Warning: is_lvalue_reference
 ›   Warning: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_reference.h:26:29:
 ›    note: 'is_lvalue_reference' declared here
 ›   Warning: struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
 ›   Warning: ^
 ›   Warning: In file included from ../src/better_sqlite3.cpp:4:
 ›   Warning: In file included from ./src/better_sqlite3.lzz:11:
 ›   Warning: In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/node.h:73:
 ›   Warning: In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8.h:24:
 ›   Warning: In file included from 
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-array-buffer.h:13:
 ›   Warning: In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-object.h:9:
 ›   Warning: /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-maybe.h:106:69: error: expected '(' 
 ›   for function-style cast or type construction
 ›   Warning: template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
 ›   Warning: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
 ›   Warning: /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-maybe.h:123:43: error: no template 
 ›   named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
 ›   Warning: template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
 ›   Warning: ~~~~~^~~~~~~~~~~~~~~~~~~~~
 ›   Warning: /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-maybe.h:123:67: error: expected '(' 
 ›   for function-style cast or type construction
 ›   Warning: In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8.h:33:
 ›   Warning: In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-function.h:11:
 ›   Warning: /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-function-callback.h:151:66: warning: 
 ›   'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
 ›   Warning: kReturnValueDefaultValueIndex - kReturnValueIndex);
 ›   Warning: , ""
 ›   Warning: /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-function-callback.h:153:50: warning: 
 ›   'static_assert' with no message is a C++17 extension [-Wc++17-extensions]
 ›   Warning: kIsolateIndex - kReturnValueIndex);
 ›   Warning: ./src/util/macros.lzz:157:21: error: no member named 'AccessorSignature' in namespace 'v8'
 ›   Warning: v8::AccessorSignature::New(isolate, recv)
 ›   Warning: ~~~~^
 ›   Warning: ./src/objects/database.lzz:180:21: warning: variable 'status' set but not used [-Wunused-but-set-variable]
 ›   Warning: int status = sqlite3_db_config(db_handle, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, 1, NULL);
 ›   Warning: ./src/util/binder.lzz:37:51: error: no member named 'CreationContext' in 'v8::Object'
 ›   Warning: v8::Local<v8::Context> ctx = obj->CreationContext();
 ›   Warning: ~~~~~^
 ›   Warning: 23 warnings and 6 errors generated.
 ›   Warning: make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
 ›   Warning: rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
 ›   Warning: gyp ERR! build error
 ›   Warning: gyp ERR! stack Error: `make` failed with exit code: 2
 ›   Warning: gyp ERR! stack     at ChildProcess.onExit 
 ›   (/Users/tim.paulaskas/.local/share/sf/node_modules/mega-linter-runner/node_modules/node-gyp/lib/build.js:203:23)
 ›   Warning: gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
 ›   Warning: gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
 ›   Warning: gyp ERR! System Darwin 23.1.0
 ›   Warning: gyp ERR! command "/Users/tim.paulaskas/.local/share/sf/client/2.17.14-31db5eb/bin/node" 
 ›   "/Users/tim.paulaskas/.local/share/sf/node_modules/.bin/node-gyp" "rebuild" "--release"
 ›   Warning: gyp ERR! cwd /Users/tim.paulaskas/.local/share/sf/node_modules/better-sqlite3
 ›   Warning: gyp ERR! node -v v20.9.0
 ›   Warning: gyp ERR! node-gyp -v v9.4.0
 ›   Warning: gyp ERR! not ok

The following errors occurred:
 ›   Error: error /Users/tim.paulaskas/.local/share/sf/node_modules/better-sqlite3: Command failed.
 ›   Exit code: 1
 ›   Command: prebuild-install || npm run build-release
 ›   Arguments: 
 ›   Directory: /Users/tim.paulaskas/.local/share/sf/node_modules/better-sqlite3
 ›   Output:
 ›   prebuild-install warn install No prebuilt binaries found (target=20.9.0 runtime=node arch=x64 libc= 
 ›   platform=darwin)
 ›
 ›   > better-sqlite3@7.6.2 build-release
 ›   > node-gyp rebuild --release
 ›
 ›   gyp info it worked if it ends with ok
 ›   gyp info using node-gyp@9.4.0
 ›   gyp info using node@20.9.0 | darwin | x64
 ›   gyp info find Python using Python version 3.11.6 found at "/usr/local/opt/python@3.11/bin/python3.11"
 ›   gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
 ›   gyp info spawn args [
 ›   gyp info spawn args   
 ›   '/Users/tim.paulaskas/.local/share/sf/node_modules/mega-linter-runner/node_modules/node-gyp/gyp/gyp_main.py',
 ›   gyp info spawn args   'binding.gyp',
 ›   gyp info spawn args   '-f',
 ›   gyp info spawn args   'make',
 ›   gyp info spawn args   '-I',
 ›   gyp info spawn args   '/Users/tim.paulaskas/.local/share/sf/node_modules/better-sqlite3/build/config.gypi',
 ›   gyp info spawn args   '-I',
 ›   gyp info spawn args   
 ›   '/Users/tim.paulaskas/.local/share/sf/node_modules/mega-linter-runner/node_modules/node-gyp/addon.gypi',
 ›   gyp info spawn args   '-I',
 ›   gyp info spawn args   '/Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/common.gypi',
 ›   gyp info spawn args   '-Dlibrary=shared_library',
 ›   gyp info spawn args   '-Dvisibility=default',
 ›   gyp info spawn args   '-Dnode_root_dir=/Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0',
 ›   gyp info spawn args   
 ›   '-Dnode_gyp_dir=/Users/tim.paulaskas/.local/share/sf/node_modules/mega-linter-runner/node_modules/node-gyp',
 ›   gyp info spawn args   
 ›   '-Dnode_lib_file=/Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/<(target_arch)/node.lib',
 ›   gyp info spawn args   '-Dmodule_root_dir=/Users/tim.paulaskas/.local/share/sf/node_modules/better-sqlite3',
 ›   gyp info spawn args   '-Dnode_engine=v8',
 ›   gyp info spawn args   '--depth=.',
 ›   gyp info spawn args   '--no-parallel',
 ›   gyp info spawn args   '--generator-output',
 ›   gyp info spawn args   'build',
 ›   gyp info spawn args   '-Goutput_dir=.'
 ›   gyp info spawn args ]
 ›   gyp info spawn make
 ›   gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
 ›     TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
 ›     ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 
 ›   ba23eeee118cd63e16015df367567cb043fed872.intermediate
 ›     TOUCH Release/obj.target/deps/locate_sqlite3.stamp
 ›     CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
 ›     LIBTOOL-STATIC Release/sqlite3.a
 ›     CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
 ›   In file included from ../src/better_sqlite3.cpp:4:
 ›   In file included from ./src/better_sqlite3.lzz:11:
 ›   In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/node.h:73:
 ›   In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8.h:24:
 ›   In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-array-buffer.h:12:
 ›   In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-local-handle.h:12:
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:465:30: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   SHARED_EXTERNAL_POINTER_TAGS(CHECK_SHARED_EXTERNAL_POINTER_TAGS)
 ›                                ^
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:465:30: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:465:30: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:465:30: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:465:30: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   PER_ISOLATE_EXTERNAL_POINTER_TAGS(CHECK_NON_SHARED_EXTERNAL_POINTER_TAGS)
 ›                                     ^
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:466:35: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:693:61: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›       static_assert(kJSObjectType + 1 == kFirstJSApiObjectType);
 ›                                                               ^
 ›                                                               , ""
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:694:55: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›       static_assert(kJSObjectType < kLastJSApiObjectType);
 ›                                                         ^
 ›                                                         , ""
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-internal.h:695:63: warning: 'static_assert' 
 ›   with no message is a C++17 extension [-Wc++17-extensions]
 ›       static_assert(kFirstJSApiObjectType < kLastJSApiObjectType);
 ›                                                                 ^
 ›                                                                 , ""
 ›   In file included from ../src/better_sqlite3.cpp:4:
 ›   In file included from ./src/better_sqlite3.lzz:11:
 ›   In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/node.h:73:
 ›   In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8.h:24:
 ›   In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-array-buffer.h:13:
 ›   In file included from /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-object.h:9:
 ›   /Users/tim.paulaskas/Library/Caches/node-gyp/20.9.0/include/node/v8-maybe.h:106:45: error: no template named 
 ›   'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
 ›     template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
 ›                                          ~~~~~^~~~~~~~~~~~~~~~~~~~~
 ›                            
    Error: /Users/tim.paulaskas/.local/share/sf/client/2.17.14-31db5eb/node_modules/yarn/bin/yarn.js add 
    sfdx-hardis@latest --non-interactive --mutex=file:/Users/tim.paulaskas/.local/share/sf/yarn.lock 
    --preferred-cache-folder=/Users/tim.paulaskas/Library/Caches/sf/yarn --check-files exited with code 1

**Comment by nvuillam** [comment]
The issue seems to happen with node-gyp dependency

https://github.com/nodejs/node-gyp#installation

What OS are you using ?

For example, if you are on Windows, you may install Python from Windows Store before being able to install sfdx-hardis

I know that Node.js also installs python in its post install scripts

This is demo-ed in this video :) https://youtu.be/LA8m-t7CjHA?si=S0HIFP71euv-6MjF&t=252

**Comment by nvuillam** [comment]
I assume that there is no issue anymore :)
