### ISSUE TITLE
hardis:org:purge:flow is failing when running the SOQL query

### ISSUE THREAD

**Issue by andynormancx** [hardisgroupcom/sfdx-hardis#49]
Running under sfdx-cli/7.90.2 darwin-x64 node-v14.15.0, when I try to use any of the Flow purging I get:

No matching Flow records found with query `SELECT Id,MasterLabel,VersionNumber,Status,Description FROM Flow WHERE Status IN ('Obsolete','Draft','InvalidDraft') ORDER BY MasterLabel,VersionNumber`

Looking at the source it appears that the Flow purging is the only functionality that makes a SOQL query. It looks like maybe the code is looking for a `records` item in the top level of the query results, whereas it appears to be under `result.records`.

I haven't had time to grab the code and debug it though, so that might be a red herring.

When I run with `--debug` I can see that the query _is_ returning results.

**Comment by nvuillam** [comment]
I'll have a look thanks for reporting :)

**Comment by andynormancx** [comment]
Thanks. I'm having a quick go at having a look myself. Not built any sfdx plugins myself yet, so a bit of a learning curve ahead to get to the point that I can debug it ;)

**Comment by andynormancx** [comment]
Awesome, thanks for fixing so quickly.

**Comment by nvuillam** [comment]
You're welcome :)
