### ISSUE TITLE
Handling of deployments for features which are only available in production

### ISSUE THREAD

**Issue by derroman** [hardisgroupcom/sfdx-hardis#520]
I'm encountering a specific challenge related to deploying opportunity layout changes using the sfdx-hardis tool. In one of my production environment, we use 'Sales Cloud Einstein for Everyone,' which adds a unique field, "Opportunity Score," to our opportunity layouts. This field is an integral part of our production layout but is not available in our sandbox environments due to the limitations of 'Sales Cloud for Everyone' in sandboxes (reference: [Salesforce Help Article](https://help.salesforce.com/s/articleView?id=000393373&type=1)).

The core issue arises when we modify opportunity layouts (both standard and Lightning) in our sandboxes and deploy these changes to production. Since the "Opportunity Score" field is not present in the sandbox metadata, deploying these changes would inadvertently remove the field from the production layouts.

I want to use this issue to discuss how to handle such scenarios where:

* A field exists in the production layout but not in the sandbox.
* Changes made to layouts in the sandbox need to be deployed to production without overwriting or removing the existing production-only fields.

This issue goes beyond the specific 'Sales Cloud Einstein for Everyone' case and could apply to any similar situation where production environments have fields or features not mirrored in sandboxes.

What strategies or methods can we employ to ensure that our deployments update layouts correctly while preserving production-specific fields? Are there specific configurations or practices within sfdx-hardis or other tools that can help us address this challenge?

**Comment by derroman** [comment]
Well, you got me: I was actually thinking about a more sophisticated "dynamic rewriting" - but this might become hard and also must be maintainable in terms of "We want to keep these fields, where they are, but the rest can be overwritten (because my deployed changes from sandboxes should be added)"...

For now the mentioned overwrite management will work, even it might not be perfect in terms of the final goal of a "one click deployment" :)

**Comment by nvuillam** [comment]
@derroman I start to know you... I edited to add the rewriting idea stuff ^^

I think it's a big new feature, and I'm not sure that the config to use it would be easier to write... but I'm open to any ideas 👼

**Comment by nvuillam** [comment]
There is something I think about for a long time: allowing to call custom commands before_deploy and after_deploy

they would be in sfdx-hardis.yml and could be scoped to branches ( in the .sfdx-hardis.main.yml config for example)

If I implement that, you could do something awful like `cp org-scope-sources/main/default/layouts/YourLayout.layout-meta.xml force-app/main/default/layouts/YourLayout.layout-meta.xml  , or we could even automate such replacement, but it would force you to maintain 2 different layout metadata files for sandboxes & production ... would it work ? ^^

**Comment by derroman** [comment]
pew... also difficult to handle, mh? Because we might have to build huge logic (either in sfdx-hardis and / or in any config to maintain this)...  and the overall value might not be worth it. 

With that said, I think it would be better to go the "package-no-overwrite.xml" way and deal with it 🤝

**Comment by nvuillam** [comment]
That's also my opinion, sometimes a few documented manual actions are better than a huge mess to implement and configure 🤣

**Comment by nvuillam** [comment]
@derroman that makes me thinks of maual actions that could be documented in a YML file, then used to generate Markdown doc, and why not mkdocs-material docuentation .... :D
