### ISSUE TITLE
Issue with  sfdx hardis:lint:access  :  Unexpected close tag Line: 9 Column: 46 Char: >

### ISSUE THREAD

**Issue by nazihachebil** [hardisgroupcom/sfdx-hardis#523]
![Image 07-12-2023 à 11 13](https://github.com/hardisgroupcom/sfdx-hardis/assets/72403363/7b4a66e1-fb9f-472e-8adc-ec4d7a8b0517)

**Comment by nazihachebil** [comment]
Thank you :)

**Comment by nvuillam** [comment]
@nazihachebil did you solve your issue ? :)
