### ISSUE TITLE
Unable to Freeze users

### ISSUE THREAD

**Issue by DezSSB** [hardisgroupcom/sfdx-hardis#530]
After following the installation video, I'm unable to freeze users.

Steps: 
* Click SFDX-Hardis extension
* Click Freeze users
* Error thrown: .
 »   Warning: hardis org user freeze is not a sf command.
Did you mean force user create? [y/n]:
 »   Error: Run sf help for a list of available commands.
![Screenshot 2023-12-12 171558](https://github.com/hardisgroupcom/sfdx-hardis/assets/152434072/be686708-0042-48e8-a673-7975bb57b4fb)

**Comment by nvuillam** [comment]
@DezSSB you don't have sfdx & sfdx-hardis installed ^^

You can use the following video -> https://sfdx-hardis.cloudity.com/#with-ide

You an also click on the refresh button of dependencies panel, then click on the message asking you if you want to install missing dependencies :)

![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/17500430/cc9a3169-9644-4e11-8d2d-e61d4d2944d3)
