### ISSUE TITLE
vscode crash with old SFDX-HARDIS dependencies

### ISSUE THREAD

**Issue by laissaouibrahim** [hardisgroupcom/sfdx-hardis#533]
Hello @nvuillam ,
I forgot to update sfdx extension dependencies.  Here is the actual situation :
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/33437f29-a59f-4687-8303-1e663b769211)

When i start vscode today, nothing work (git  extension,sfdx CLI extension...). i got this error when i go to **Helper ==> Developer Tools** 
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/4989841e-eafa-48fb-a2dc-76dbf2f7a63f) 
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/f4bd509f-d726-4fab-9ab8-07bf97acf830)
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/77bcc311-0dc1-4600-b6f4-017f8a8d07e5)

I can understand that i should always have recent version of the extension dependencies. But if i forgot to do it, I think i will be better to keep vscode working until i update sfdx extension :). 

Now i'm trying to update all dependencies to check if it will resolve my issue.

thanks for your help.

**Comment by nvuillam** [comment]
Are you inside a git repo ?
If you cliquk on the error in the console, please can you screenshot the lines triggering the errors ?

I don't think it's related to the fact that extensions are not up to dare ^°

**Comment by laissaouibrahim** [comment]
No i'am inside vscode. I check his Log based on :
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/21e15999-ee85-41d9-bc87-c4a13a604885)
Do you mean this :
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/b8ebcb78-c1dc-4c8e-a3e7-a744fa1095e2)

**Comment by nvuillam** [comment]
Or what is in your sfdx.log ?

I need to find where this "branch" property is called ^^

**Comment by laissaouibrahim** [comment]
I found nothing in .sfdx/sfdx.log
When i use sfdx to retreive meta data. i got this error :
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/2a160ebf-309b-4bf6-bd29-5d92a9093622)
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/9dd3ba21-a6c8-48df-8e4c-1cf5536d4204)

When i disable SfdxHardis. SFDX CLI work again.
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/2a957180-a3bd-4098-beb1-d67ca1086585)
![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/43149687/c38dbb14-effa-4f1b-a7c5-c4a0f9d7ac36)

**Comment by nvuillam** [comment]
Is your VsCode open with the git repo as root, or do you have multiple folders in your workspace ?

**Comment by laissaouibrahim** [comment]
yes i'm already working on git repo as root. i have deleted my old local git repo folder and i have created a new one.
for now it work . i'll keep monitoring vscode. 
thanks :)

**Comment by nvuillam** [comment]
Probably your local git repo was broken, and it messed with extensions, including sfdx-hardis ^^
