### ISSUE TITLE
Org Monitoring email not sending to multiple recipients

### ISSUE THREAD

**Issue by AlainBatesNovuna** [hardisgroupcom/sfdx-hardis#562]
I've setup the Org Monitoring pipeline in Bitbucket and have attempted to specify multiple email addresses as a comma-separated string in the NOTIF_EMAIL_ADDRESS repository variable (e.g. email1@test.com,email2@test.com). However, on the Apex Tests step, no email is being sent and the below entries are appearing in the build logs. The emails work fine when I just specify a single email address, so the issue is something to do with parsing multiple email addresses. It looks like the Salesforce SOAP service expects multiple emails to be sent in the request body as an array, but the email provider is currently sending them as a comma-separated string.

[sfdx-hardis] [NotifProvider] - Notif target found: sfdx-hardis Email connector
[sfdx-hardis] [EmailProvider] Error while sending email to email1@test.com,email2@test.com
[sfdx-hardis] {
  "soapenv:Envelope": {
    "$": {
      "xmlns:soapenv": "http://schemas.xmlsoap.org/soap/envelope/",
      "xmlns": "urn:enterprise.soap.sforce.com",
      "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"
    },
    "soapenv:Header": {
      "LimitInfoHeader": {
        "limitInfo": {
          "current": "11759",
          "limit": "5000000",
          "type": "API REQUESTS"
        }
      }
    },
    "soapenv:Body": {
      "sendEmailResponse": {
        "result": {
          "errors": {
            "fields": [
              "toAddresses",
              "email1@test.com,email2@test.com"
            ],
            "message": "Email address is invalid: email1@test.com,email2@test.com",
            "statusCode": "INVALID_EMAIL_ADDRESS",
            "targetObjectId": {
              "$": {
                "xsi:nil": "true"
              }
            }
          },
          "success": "false"
        }
      }
    }
  }
}

**Comment by nvuillam** [comment]
@AlainBatesNovuna good catch, thanks for reporting :)

PR is on the way !

**Comment by nvuillam** [comment]
@AlainBatesNovuna I just released v4.28.1 with a fix, please can you check and confirm it's now org with multiple recipients ? :)

**Comment by AlainBatesNovuna** [comment]
@nvuillam I've re-run the pipeline and it works now! Thanks very much for the rapid fix :)

**Comment by nvuillam** [comment]
You're welcome :)
