### ISSUE TITLE
Command to detect active users who has not logged in for N days (so licenses could be spared)

### ISSUE THREAD

**Issue by nvuillam** [hardisgroupcom/sfdx-hardis#575]
Example: sfdx hardis:org:diagnose:unusedusers --days 365

Default value for days: 100

Outputs:
- list of users in console with last connexion date
- CSV report: example -> https://github.com/hardisgroupcom/sfdx-hardis/blob/6be7cc51d6b2894fc77fee23626786decd2ffce8/src/commands/hardis/org/diagnose/audittrail.ts#L342
- Slack / Teams / Mail notification: example -> https://github.com/hardisgroupcom/sfdx-hardis/blob/6be7cc51d6b2894fc77fee23626786decd2ffce8/src/commands/hardis/org/diagnose/audittrail.ts#L358

**Comment by masaner** [comment]
@nvuillam This has been implemented, we can close it.
