### ISSUE TITLE
Salesforce Extension pack command error

### ISSUE THREAD

**Issue by anthonygiuliano** [hardisgroupcom/sfdx-hardis#583]
> 🦙 Salesforce Extension pack command error. If it is installed, just wait for it to be initialized :) Detail: command 'sfdx.start.apex.debug.logging' not found

Hello, at some point maybe 1-2 weeks ago, I started getting this warning/error when trying to "Activate debug logs tracing". Here's what I see under dependencies, and my os, vscode versions, etc. Any idea what's going on? Let me know if there's any logs that would be helpful to see. Thanks!

**SFDX**
@salesforce/cli v2.37.4
@salesforce/plugin-packaging v2.4.0
sfdmu v4.33.7
sfdx-essentials v2.12.0
sfdx-git-delta v5.38.4
sfdx-hardis v4.31.2
texei-sfdx-plugin v2.4.1

**Core**
Node.js v20.11.1
Git v2.39.3 (Apple Git-146)

**VsCode Extensions**
Salesforce Extensions Pack

**Visual Studio Code**
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:43:08.196Z (1 wk ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**About This Mac**
Chip: Apple M1 Pro
MacOS: 14.4.1 (23E224)

**Comment by nvuillam** [comment]
mmm I hope that while switch from sfdx to sf, VsCode Replay Debugger authors did not also change the name of the command sfdx.start.apex.debug.logging :)

I'll check :)

**Comment by nvuillam** [comment]
@anthonygiuliano it was what I was guessing... :)

The fix is tested and published on VsCode SFDX Hardis 2.8.0 (restart your VsCode)

If you have an issue with running debugger, you can use this workaround -> https://github.com/forcedotcom/salesforcedx-vscode/issues/5087#issuecomment-1717366728
