### ISSUE TITLE
Problem git status

### ISSUE THREAD

**Issue by psagredo99** [hardisgroupcom/sfdx-hardis#625]
Hi,

First, im new into sfdx hardis and visual studio development. I have read all the documentation and I have been stuck at this point for days. When creating a new task I get this error constantly.

![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/72439144/851c50f7-d2c7-4db8-88b9-4be3f3e26714)

I have git installed and the connection is with azure devops. I can also see that the git status section is empty. It's probably stupid but I can't make any progress.

Greetings and thanks in advance.

**Comment by nvuillam** [comment]
Just create a first commit with just the README.md for example, then you won't have this error anymore :)

The pre-requisites to install sfdx-hardis are to have some experience with git & Salesforce CLI

If you don't have it yet, you should ask someone who does to make the install for you :)

**Comment by psagredo99** [comment]
Thank you for taking the time to reply,

It is indeed an error in the repository, I close the issue.

Sorry for the inconvenience caused .

**Comment by nvuillam** [comment]
@psagredo99 no problem i'm here to help :)
