### ISSUE TITLE
Error Cannot read properties of undefined when creating new task.

### ISSUE THREAD

**Issue by psagredo99** [hardisgroupcom/sfdx-hardis#630]
Hi,

I have been testing the tool and learning some git, it actually works like a charm but i have a small issue.

When trying to "Start a new task" all goes fine until last etep where command executes where i get :

**ERROR running hardis:work:new:  Cannot read properties of undefined (reading 'includes')**

I suppose is some kink of file or configuration that is not being able to find but i have no clue on where to look or reserach. . Ive tried to start project from 0 and same issue.

Any clue? Thanks in advance for any help and dont want to disturb (=

Also a question i usually get, ¿how do i know if a task has been created or in which task im currently working? ¿It is defined by the branch im working on?

![image](https://github.com/hardisgroupcom/sfdx-hardis/assets/72439144/8c488998-2dab-4776-ba8a-84d3c36a47c2)

**Comment by nvuillam** [comment]
Please can you share your .sfdx-hardis.yml ?

**Comment by nvuillam** [comment]
No response probably means that the issue is solved ? If not, please ask that we reopen the issue :)
