### ISSUE TITLE
When quick-deploy do not run unit test for deployment

### ISSUE THREAD

**Issue by maximeg44** [hardisgroupcom/sfdx-hardis#639]
When transitioning from a minor to a major branch and the quick-deploy is no longer available (due to a prior deployment invalidating it), we currently perform a deployment with test classes execution. It is preferable not to rerun the test classes because the branch has already been merged, which doesn't provide any benefit to the team that will still encounter the issue. This situation is marginal, unlike the invalidation of quick-deploy.

Desired behavior: If quick-deploy fails between minor and major, then initiate the deployment without running test classes.

See the class : https://github.com/hardisgroupcom/sfdx-hardis/blob/89dcd95abacee6d9c2793f005d205da0b6915bed/src/common/utils/deployUtils.ts

**Comment by nvuillam** [comment]
Done ! cc @maximeg44
