### ISSUE TITLE
PMD Ruleset Configuration Error and Technical Definition Visibility Loss in Pipeline

### ISSUE THREAD

**Issue by yamioliva** [hardisgroupcom/sfdx-hardis#643]
Hey team, we've run into an issue with the PMD ruleset configuration while using the `sfdx-hardis` plugin.

So, here's what's happening:

1. We run the pipeline with the `sfdx-hardis` plugin.
2. We hit a PMD ruleset configuration error.
3. To get around it, we modified the YAML file to skip the problematic section.
4. But now, we're missing the technical definitions in our pipeline, which we really need.

**Expected Behavior:**

The PMD ruleset should run without errors, and the technical definitions should be visible in the pipeline.

**Actual Behavior:**

- PMD ruleset configuration errors happen. 
Or
- Technical definitions disappear from the pipeline after applying the workaround.

**Screenshots:**

Initial Error in PMD Ruleset Configuration:
![Initial Error in PMD Ruleset Configuration](https://github.com/hardisgroupcom/sfdx-hardis/assets/38166991/0975401e-8f0b-4eec-8ef4-27c20e0792d2)

Configuration Workaround:
![Configuration Workaround](https://github.com/hardisgroupcom/sfdx-hardis/assets/38166991/a8accbd6-0210-477a-995e-1ce7f0cb0521)

Missing Technical Definitions in Pipeline:
![Missing Technical Definitions in Pipeline2](https://github.com/hardisgroupcom/sfdx-hardis/assets/38166991/01bf2124-7d5f-43de-b289-ac6ec6c9f30b)

![Missing Technical Definitions in Pipeline](https://github.com/hardisgroupcom/sfdx-hardis/assets/38166991/7fdf172c-7772-4c68-b020-4cae86852ecc)

PMD Ruleset XML Configuration:
![PMD Ruleset XML Configuration](https://github.com/hardisgroupcom/sfdx-hardis/assets/38166991/bb650e6b-f302-4572-abc2-bd5346f62915)

**Environment:**

- **Plugin:** sfdx-hardis
- **Tool:** MegaLinter
- **Configuration:** PMD Ruleset, Docker

**Additional Context:**

We applied the workaround by skipping the error in the YAML file, which fixed the initial problem but caused us to lose the technical definition visibility in the pipeline.

We're looking for help to solve the PMD ruleset configuration error without losing the technical definitions in the pipeline. Has anyone else faced this? Any known fixes?

Thanks for your support!

**Comment by nvuillam** [comment]
hi @yamioliva :)

I think it's related to the newest version of MegaLinter, that contains sfdx-scanner v4, that contains PMD7 (previous was PMD6)

Some PMD6 rules has been removed, so you can just remove the crashing part (the custom Xpath rule) in your PMD ruleset XML file, and it should be ok :)

Best regards

**Comment by nvuillam** [comment]
@yamioliva I think I solved the issue on the online default PMD rulesets file :)

Please can yo ucheck again ? :)

**Comment by yamioliva** [comment]
Hi Nico,

Thanks for the quick response!

Ok! I’ll keep you posted on the outcome.

Best regards,
Yamilet

**Comment by yamioliva** [comment]
Hi Nico,

Petite question. I understand that removing the custom XPath rule might fix the immediate problem, but this rule helps us a lot. It ensures we don't hardcode callout endpoint URLs in our Apex code, and instead, use Named Credentials. This is important for keeping our code secure and flexible.

I want to make sure we keep this functionality. **Does MegaLinter have a similar rule** or check that enforces this practice? If not, is there a way to update or adapt this rule to work with PMD7 in MegaLinter?

Your help would be really appreciated.

Thanks!
Yamilet

**Comment by nvuillam** [comment]
@yamioliva I don't know if it is a default PMD7 rule, I'll have a look :)

ps: maybe @maximeg44 know ^^

**Comment by yamioliva** [comment]
> @yamioliva I don't know if it is a default PMD7 rule, I'll have a look :)
> 
> ps: maybe @maximeg44 know ^^

Ok, thanks!

**Comment by yamioliva** [comment]
Hi Nico,

The error persists even after removing the custom rule. Here is the current error message:

```
Error (1): No files were found in the target. --target must contain at least one file.
```

Attached is a screenshot of the current error.

Could you please provide further guidance on how to resolve this issue?

Thank you!

![image](https://github.com/user-attachments/assets/0e5f6d00-fe35-4132-8ec5-1e98a996f99a)

**Comment by nvuillam** [comment]
@yamioliva hmmm sfdx-scanner is not great for Aura / LWC ... 

I'm in vacations, before we make a call when I come back, I suggest you disable this linter by adding the following line in your .mega-linter.yml :)

```yaml
SALESFORCE_SFDX_SCANNER_LWC_DISABLE_ERRORS=true
```

**Comment by yamioliva** [comment]
@nvuillam no problem, as I mentioned in my initial description, I have already done that to avoid errors during deployments. However, this prevents the technical definition from being displayed. I just wanted to solve the error, but of course, it can wait ;)
Thank you! Have a great holiday!
