### ISSUE TITLE
Document options in sfdx hardis:project:create

### ISSUE THREAD

**Issue by readeral** [hardisgroupcom/sfdx-hardis#667]
Hi there,

Just getting on board with your project, thanks so much for developing it!

I have found the onboarding experience a little difficult, especially stepping through Init SFDX project, as some of the prompts under hardis:project:create were unclear to me what they did and what I should choose. For example, when prompted for the base URL it was presented as:
```
What is the base URL of the org you want to connect to, as DevHub_MyProject?
Custom login URL
- The best choice :) Example: https://myclient--preprod.sandbox.lightning.force.com/
Other: Dev org, Production org or DevHub org (login.salesforce.com)
- The org I want to connect is NOT as sandbox
```
But my questions at that step were:
What does "base URL" represent here, and what is DevHub_MyProject (an alias? a user?)?
_Why_ is the best choice to select a sandbox? What problems I might face if I choose my DevHub instead? (which is what I ended up doing).

If you can document what this step is doing, then it will be easier to decide which option to select.

**Comment by nvuillam** [comment]
@readeral thanks for your feedback :)

In your case, you need a DevHub only if you want to use scratch orgs.
Indeed, when prompting for a base URL for DevHub, it should allow only production orgs and not sandboxes, I'll fix that :)

If you want to use only sandboxes, you don't need to define a DevHub

**Comment by readeral** [comment]
Hi Nicolas,

My main feedback is right at that first point of init a sdfx project. As I
progressed through authorising my various orgs, the options for authorising
made more sense, and I could then understand that prompt was being reused.

Having initialised a regular sdfx project without hardis I probably could
have deduced it wasn’t some sort of permanent consideration, but I think
for that first step it probably should have a little more guidance in the
prompt.

**Comment by nvuillam** [comment]
@readeral solved in latest version, I made the messages more explicit :)

```ts
 const customLoginUrlExample =
    orgTypes && orgTypes.length === 1 && orgTypes[0] === "login"
      ? "https://myclient.lightning.force.com/"
      : "https://myclient--preprod.sandbox.lightning.force.com/";
  const allChoices = [
    {
      title: "📝 Custom login URL (Sandbox, DevHub or Production Org)",
      description: `Recommended option :) Example: ${customLoginUrlExample}`,
      value: "custom",
    },
```

Don't hesitate to post other feedbacks and enhancements propositions :)
