### ISSUE TITLE
YAML v8r no schema for user files

### ISSUE THREAD

**Issue by readeral** [hardisgroupcom/sfdx-hardis#773]
YAML v8r cannot find a schema to validate .config/user/.sfdx-hardis.name.yml

**Comment by nvuillam** [comment]
./config/user/ should be added in your local .gitignore, those files are useful locally but do not need to be committed :)

**Comment by readeral** [comment]
Oh great. A documentation opportunity? I’ll make a PR once I’m back behind
my computer.

**Comment by nvuillam** [comment]
@readeral I'll be glad to accept the PR ,thanks :)

**Comment by readeral** [comment]
@nvuillam it seems you already have the code to do this automatically as part of the init hook (check-local-sfdx-hardis-files.ts), but this hook isn't ever triggered?

**Comment by nvuillam** [comment]
@readeral I don't remember why I disabled the hook

```yaml
  // Disable this hook for now
  if ((process.env?.AUTO_UPDATE || 'false') !== 'true') {
    return;
  }
```

I'll try to reactivate it for v5 , maybe just when we run certain commands used only by Release Managers, like https://sfdx-hardis.cloudity.com/hardis/project/configure/auth/  :)
