### ISSUE TITLE
Bug v5 : Save my current task authentication

### ISSUE THREAD

**Issue by mamasse19** [hardisgroupcom/sfdx-hardis#777]
![image](https://github.com/user-attachments/assets/08af87e6-0938-485c-b3cb-3484c1ef2936)

**Comment by nvuillam** [comment]
@mamasse19 please can you share the full console log from the start of the command ? :)

**Comment by mamasse19** [comment]
Full console log :)
![image](https://github.com/user-attachments/assets/3f6917bc-719b-4ba5-97bb-0c440c9a8a14)

**Comment by nvuillam** [comment]
@mamasse19 plz can you run `sf org display --json` and post the result here ? ( hide anything looking like auth tokens ^^ )

**Comment by mamasse19** [comment]
Here you go :)
![image](https://github.com/user-attachments/assets/a349ac67-edab-477d-890f-c59a6d717d2c)

**Comment by nvuillam** [comment]
If you use "select another org" and connect again to your org (don't pick the default org on the first prompt), and if you try again save/publish my current task, how does it go ?

**Comment by nvuillam** [comment]
Solved according to our private messages :)

Please reopen if you see the issue again :)
