### ISSUE TITLE
New task - EVOL - Default org (solved)

### ISSUE THREAD

**Issue by mamasse19** [hardisgroupcom/sfdx-hardis#778]
Dans l'écran d'authentification, il nous est demandé de choisir une org à authentifier. 
Je me dis qu'il serait peut-être bien d'ajouter l'option "Use default org"

**Comment by nvuillam** [comment]
@mamasse19 this will be available in the next alpha patch :)

![image](https://github.com/user-attachments/assets/ebdaf2f1-08e0-469c-b001-7f712d2c652c)
