### ISSUE TITLE
v5 - Save my current task - EVOL - Authentification org

### ISSUE THREAD

**Issue by mamasse19** [hardisgroupcom/sfdx-hardis#780]
Ecran "entrer URL de l'org" : une fois l'URL entrée, nous sommes redirigés vers l'URL. On nous redemande de s'authentifier alors que l'org a déjà été authentifiée via les commandes du plug in. 
Est-ce qu'il serait possible de se passer de cette double saisie ?

**Comment by nvuillam** [comment]
Will be solved in https://github.com/hardisgroupcom/sfdx-hardis/issues/777 , no authentication will be prompted :)
