### ISSUE TITLE
[Plugin warning] Remove the warning if 'Salesforce extension pack (expanded)' is installed

### ISSUE THREAD

**Issue by mickaelgudin** [hardisgroupcom/sfdx-hardis#782]
remove the warning if 'Salesforce extension pack (expanded)' is installed it's basically the same as Salesforce extension pack

![image](https://github.com/user-attachments/assets/8ad25a6f-4441-4c55-b588-e4b1a77028ed)

**extension in the vscode market :** salesforce.salesforcedx-vscode-expanded

**Comment by nvuillam** [comment]
@mickaelgudin thanks for reporting :)
Will be solved in next version of VsCode SFDX Hardis :) ( already available as pre-release)
