### ISSUE TITLE
Bug (Alpha) Cannot read properties of undefined (reading 'debugMode')

### ISSUE THREAD

**Issue by readeral** [hardisgroupcom/sfdx-hardis#788]
When using alpha build v5.0.1-alpha202409162139.0, `sf hardis:org:data:delete` throws the following error:
```
Cannot read properties of undefined (reading 'debugMode')
```

Issue is not present running in v4.53.0

I've chased it down and the error is throwing at [orgUtils.ts line 584](https://github.com/hardisgroupcom/sfdx-hardis/blob/b7fa633718332c0a1e0c53225644b1379c5f18e3/src/common/utils/orgUtils.ts#L583), `this` is undefined. 

Perhaps it hasn't become evident because jsforce connection is normally available, and maybe it could be because of how I've installed the alpha plugin that it uses CLI command instead? But even so, the CLI command is failing

**Comment by nvuillam** [comment]
@readeral thanks for reporting :)
I just fixed it, i'll release it in the next alpha :)

**Comment by nvuillam** [comment]
@readeral solved in latest alpha, if you want to try :)
