### ISSUE TITLE
Commands always go to Auth flow ignoring default or even --targetusername

### ISSUE THREAD

**Issue by alesremta-ext43767** [hardisgroupcom/sfdx-hardis#800]
Tested with several commands. Whichever command I run it always goes to authorising an org first. It seems to go over existing authorisations first (assuming, see output below) but still asks whether to go to Scratch org or Prod and launches the OAuth flow.

I tried `--targetusername` or `--target-org` or leaving it out to fall back on default and all behaves the same.

Also, adding `--no-prompt` does not seem to help and the interactive version of the script launches and goes to auth flow.

SF CLI Version: @salesforce/cli/2.58.7 darwin-arm64 node-v20.8.0
sfdx-hardis Version: 5.0.5

```
terminal % sf hardis org purge flow --status Obsolete --no-prompt --targetusername core
[sfdx-hardis][command] sf org display --target-org core --json
[sfdx-hardis] You must be connected to org  to perform this command. Please login in the open web browser
? 🦙 What is the base URL or the org you want to connect to, as  ? (Use arrow keys)
❯ 📝 Custom login URL (Sandbox, DevHub or Production Org)
  🧪 Sandbox or Scratch org (test.salesforce.com)
  ☢️ Other: Dev org, Production org or DevHub org (login.salesforce.com)
  ⛔ Exit this script
```

**Comment by nvuillam** [comment]
@alesremta-ext43767 what is the output of `sf org display --target-org core --json` ? (hide tokens ^^)

Note: it's not a solution, maybe just a workaround, but --skipauth should... skip auth

**Comment by alesremta-ext43767** [comment]
> `sf org display --target-org core --json`
The JWT token is definitely valid. I use it a bunch to open the org and do other deploys.
```
{
  "status": 0,
  "result": {
    "id": "00DRR000XXXXXXX",
    "devHubId": "ales.remta@xxxxx",
    "apiVersion": "61.0",
    "accessToken": "XXXXXXXXWDt!AQEAQXXXXXXXXXX",
    "instanceUrl": "https://newport-bigdipper-8879.scratch.my.salesforce.com",
    "username": "XXXXXXX@example.com",
    "clientId": "PlatformCLI",
    "status": "Active",
    "expirationDate": "2024-10-07",
    "createdBy": "sfc_devhub@XXXXX.cz",
    "namespace": "XXX",
    "orgName": "XXXXX",
    "createdDate": "2024-09-20T04:09:00.000+0000",
    "signupUsername": "test-uydfb6qqt3sk@example.com",
    "alias": "core"
  },
  "warnings": [
    "This command will expose sensitive information ...."
  ]
}
```

**Comment by nvuillam** [comment]
@alesremta-ext43767 ok I get it, sfdx-hardis looks for a property connectedStatus and it does not find it... 

That's really strange

```
$ sf org display --target-org nicolas.vuillamy@cloudity-xxx.com.integci --json
 »   Warning: sfdx-hardis is a linked ESM module and cannot be auto-transpiled. Existing compiled source will be used instead.
{
  "status": 0,
  "result": {
    "id": "xxxxx",
    "apiVersion": "62.0",
    "accessToken": xxxxx",
    "instanceUrl": "https://xxxxx.sandbox.my.salesforce.com",
    "username": "nicolas.vuillamy@cloudity-xxxxx.com.integci",
    "clientId": "PlatformCLI",
    "connectedStatus": "Connected"
  },
  "warnings": [
    "This command will expose sensitive information that allows for subsequent activity using your current authenticated session.\nSharing this information is equivalent to logging someone in under the current credential, resulting in unintended access and escalation of privilege.\nFor additional information, please review the authorization section of the https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_web_flow.htm."      
  ]
}
```

Please can you run `sf version --json --verbose` and send the result here ?

**Comment by nvuillam** [comment]
@alesremta-ext43767 do you still have the issue ?

**Comment by alesremta-ext43767** [comment]
> @alesremta-ext43767 do you still have the issue ?
Thanks for checking back @nvuillam. I was using the --skip-auth argument and had no issues then. Tried today without it and it seems to be working well too. So no issue!

**Comment by nvuillam** [comment]
@alesremta-ext43767 thanks for your feedback, i'm glad to know you don't have the issue anymore :)
