### ISSUE TITLE
Export Files from org doesn't work anymore

### ISSUE THREAD

**Issue by CedricLTL** [hardisgroupcom/sfdx-hardis#809]
Hello,

I have been experiencing a problem for a few days with the file export script.
Indeed, it no longer works and gives me the error below each time I launch it. Last time it worked was on 09/20/2024. I am using the latest version of Hardis and all the plugins are up to date.

Thank you very much for your help.

![2024-09-30_10-54-27](https://github.com/user-attachments/assets/5fb47fb6-eda6-42ba-a9ab-afe435a1c6ee)

**Comment by nvuillam** [comment]
There is probably an issue with BulkApiV2 (before sfdx-hardis v5 we used BulkApiV1 internally)

I'll try to reproduce and have a look, meanwhile u can downgrade to the latest v4

**Comment by CedricLTL** [comment]
Thank you very much for your answer Nicolas.
By the way it does not allow me to rollback to v4, only on V2.12.1
![image](https://github.com/user-attachments/assets/5a214893-b240-423a-84c0-03c97fd2a358)


I tried with this version and i've got the same problem.
Thanks for help

**Comment by nvuillam** [comment]
I just runned it on 19K opportunities and it works well with latest versions, I don't succeed to reproduce your issue, is it still happening ?

Can you share your `export.json` ?

**Comment by CedricLTL** [comment]
Thank you so much @nvuillam !
Everything works back again after the command line to downgrade the SF cli plugin ;)
By the way, impossible to make it work with latest version.... 

Here my export.json

```
{
  "sfdxHardisLabel": "Export Files Accounts",
  "sfdxHardisDescription": "Export files Accounts",
  "soqlQuery": "SELECT Id,Name,ExportName__c FROM Account",
  "fileTypes": "all",
  "outputFolderNameField": "ExportName__c",
  "outputFileNameFormat": "title",
  "overwriteParentRecords": true,
  "overwriteFiles": true
}
```
i've got another bonus question, the last! 
Is it possible to custom the "outputFileNameFormat"? Ex : custom field - title
