### ISSUE TITLE
hardis:org:user:activateinvalid not working

### ISSUE THREAD

**Issue by paferpotest** [hardisgroupcom/sfdx-hardis#876]
Hi,

After running the option to activate users with .invalid, I don't get a popup asking about which users/profiles I want to activate.

Instead, the process runs with a wrong query and doesn't found any users:

sfdx-hardis] Querying User records with email ending with .invalid...
[sfdx-hardis] SOQL REST: SELECT Id FROM Profile WHERE Name IN ('') on https://testpablo.sandbox.my.salesforce.com/
[sfdx-hardis] [BulkApiV2] SELECT Id,Name,Username,Email,ProfileId FROM User WHERE Email LIKE '%.invalid' and IsActive=true and ProfileId IN ('')
✔ [BulkApiV2] Bulk Query completed with 0 results.
[sfdx-hardis] No matching user records found with email ending with .invalid

**Comment by nvuillam** [comment]
Thanks for reporting, I succeeded to reproduce, i'm on it :)

**Comment by nvuillam** [comment]
@paferpotest fixed in 5.6.1

It was related to the updated way of handling default values by SF Cli architecture, so the bug was here since sfdx-hardis v5 😨 

Please can you confirm it's now ok with your use case ? :)

**Comment by paferpo** [comment]
That was quick, it's working well now, thanks!

**Comment by nvuillam** [comment]
@paferpo the fix was very simple :)
