### ISSUE TITLE
Error in `check_quality` Job During Validation Pipeline

### ISSUE THREAD

**Issue by yamioliva** [hardisgroupcom/sfdx-hardis#879]
Hello, 

We encountered an error in the `check_quality` job during the validation pipeline while using **sfdx-hardis**. The job failed with the following error message:

```
❌ Linted [REPOSITORY] files with [trivy]: Found 1 error(s) - (17.39s)

- Using [trivy v0.56.2] https://megalinter.io/8.1.0/descriptors/repository_trivy
- MegaLinter key: [REPOSITORY_TRIVY]
- Rules config: identified by [trivy]

--Error detail:
2024-11-15T08:26:11Z ERROR [vulndb] The first run cannot skip downloading DB
2024-11-15T08:26:11Z FATAL Fatal error init error: DB error: database error: --skip-update cannot be specified on the first run.

```

It appears that the Trivy linter is failing because it cannot skip downloading the database on the first run. The specific error is:

```
ERROR [vulndb] The first run cannot skip downloading DB
FATAL Fatal error init error: DB error: database error: --skip-update cannot be specified on the first run.
```
Could you please assist us in resolving this issue? 🙏 

Thank you! 😃

**Comment by nvuillam** [comment]
@yamioliva a new version of MegaLinter has been released (v8.2.0) and contains a workaround related to trivy's instability, please can you try again ? :)

**Comment by yamioliva** [comment]
Hi Nico,  

Thanks for the quick response and for pointing out the MegaLinter update! I retried the job with version 8.2.0, and it looks like Trivy is no longer causing issues, which is great—so thanks for that!  

However, after re-running the pipeline, a new issue popped up in the `check_quality` job. While Trivy now runs smoothly, the job is flagging several new non-blocking warnings and errors that we didn’t see before.  

Here’s a summary of the key points:  
1. **BASH with shfmt**: One non-blocking error related to a missing newline in `.husky/pre-commit`.  
2. **JSON with Prettier**: Formatting warnings in several files, like `package.json` and `sfdx-project.json`.  
3. **YAML with yamllint**: Multiple warnings and errors, including missing document starts (`---`), trailing spaces, and indentation issues in `.gitlab-ci.yml` and several `azure-pipelines-*.yml` files.  

The weird part is that we haven’t made any changes to the repo, so these warnings and errors are new since the MegaLinter update. It makes me think the update may have introduced stricter checks or changes in default configurations.  

Do you know if that’s the case? Or if there’s something we could tweak in the `.mega-linter.yml` file to reduce the noise while keeping things stable? Let me know what you think—I’d appreciate any tips!  

Thanks as always! 😊  

![image](https://github.com/user-attachments/assets/1883034e-c53f-4ecc-bb9c-e65643a234e8)
 
![image](https://github.com/user-attachments/assets/31452e5a-b4f1-4fa5-bc31-e5344f71fcd5)

**Comment by nvuillam** [comment]
@yamioliva it should be ok except prettier :)
