### ISSUE TITLE
Unable to run 'sf hardis:org:diagnose:legacyapi'

### ISSUE THREAD

**Issue by awesomeandrey** [hardisgroupcom/sfdx-hardis#889]
Hi there 

Recently made a decision to try out SF Hardis plugin since it allows to track components with obsolete API version.

I followed the instructions at https://nicolas.vuillamy.fr/handle-salesforce-api-versions-deprecation-like-a-pro-335065f52238.

Here is the command I used to install the plugin: `sf plugins install sfdx-hardis`

Next I invoked `sf hardis:org:diagnose:legacyapi -u MyScratchOrgAlias` to run the diagnosis based on my newly generated scratch org (SO). The SO was generated via native SF CLI commands.

As a result, the CLI asked me to log into SO. The login was granted and then I saw the following error log in terminal:

<img width="1614" alt="image" src="https://github.com/user-attachments/assets/a17719a3-19c9-48d9-bc38-d97aa056a24f">

The error message says _Error (10): Cannot create property 'name' on string 'so'_ where 'so' is an alias for my scratch org.

I tried running the hardis command against DevHub environment but the result was the same.

Is there anything wrong I'm doing? 

Additional info:
- OS = Mac (14.6.1)
- SF CLI = @salesforce/cli/2.66.7 darwin-x64 node-v21.4.0 (installed via npm)

Thanks!

**Comment by awesomeandrey** [comment]
UPD: I opened the project through VS Code, installed the extension, and invoked the legacy API check via GUI.

<img width="1760" alt="image" src="https://github.com/user-attachments/assets/119c8cc4-3704-40da-8e2f-d3839fb62666">

The outcome hasn't changed((

**Comment by nvuillam** [comment]
@awesomeandrey the bug after the first login is a known problem.... that I never succeeded to reproduce :'( :'( :'( 

I'm pretty sure that if you run again the command from the VsCode SFDX Hardis menu it will work, please can you confirm ?

Best regards

**Comment by awesomeandrey** [comment]
@nvuillam Thanks for the response

Here's another round of testing `sf hardis:org:diagnose:legacyapi` from me!

Environment info:
- macOS `Sonoma 14.6.1`
- VS Code `Version: 1.95.3`
- Salesforce CLI `@salesforce/cli/2.66.7 darwin-x64`
- Node `v21.4.0`

Below is the full list of SF plugins installed locally (`sf plugins` command result):
```
@salesforce/commerce 250.1.0
@salesforce/sfdx-scanner 4.6.0
community 2.4.9 (2.4.9)
packaging 2.9.3
sfdmu 4.36.7
sfdx-git-delta 5.49.4
sfdx-hardis 5.7.1
texei-sfdx-plugin 2.8.1
```

I opened the project via Visual Studio Code and clicked on _Legacy API versions usage_ through the GUI (see the screen below):

<img width="1671" alt="image" src="https://github.com/user-attachments/assets/0615abd9-0d8e-4ef1-8cbd-db0c801ee879">

Next I logged into scratch org via Web flow, but the result has not changed -- the error is still present:

<img width="1690" alt="image" src="https://github.com/user-attachments/assets/a9917e44-c742-4817-a341-26012476a2d0">

**Comment by awesomeandrey** [comment]
The error message seems to be purely related to JavaScript issue.

Googling the error message led me to this [post that replays the error message](https://stackoverflow.com/questions/41510186/cannot-create-property-on-string).

After thinking through it for a moment I came up with my pseudo-vision of the place in **_hardis_** repo that might be the root cause. Below is the conceptual view of the problematic script/place in codebase:
```
let targetOrgAlias = "so"; // input parameter
let nameProp = "name"; // static 'name' property name

let connection = { [nameProp]: targetOrgAlias, "instanceUrl": "https://..." };
let orgConnections = {};
orgConnections[targetOrgAlias] = targetOrgAlias;
orgConnections[targetOrgAlias][nameProp] = connection; // this is where error comes up
```
Running this JS script results in the same error message - _Cannot create property 'name' on string 'so'_ (where 'so' is an alias for my scratch org).

Looks like [this file](https://github.com/hardisgroupcom/sfdx-hardis/blob/main/src/commands/hardis/org/diagnose/legacyapi.ts) is an entry point for `sf hardis:org:diagnose:legacyapi` command. I think this file is the 1st candidate to check/review in order to find the resolution.

**Comment by nvuillam** [comment]
Thanks for the great investigation, I'll do my best to solve it :)

Meanwhile, you can select a default org using menu Status -> Select another org, then run the command

![image](https://github.com/user-attachments/assets/5acc2ed5-1c75-4158-b083-094fd3d0760b)

Are you in a SFDX project folder , or any random folder ?

**Comment by nvuillam** [comment]
I succeed to reproduce it !!! (by being out of a SFDX project folder)
Fix on the way :)

**Comment by awesomeandrey** [comment]
@nvuillam sounds good

nevertheless, the hardis commands were run from SFDX root folder

Here's project structure I have:
```
├── project-name
   ├── config
   ├── src
       ├── p1
       ├── p2
   ├── package.json
   ├── sfdx-project.json
```

the commands were run from `project-name` folder (`pwd` command results with `/Users/.../Projects/project-name`)

What if the sources folder should be named `force-app`? Can it be the root cause? Because mine one is named `src`.

**Comment by nvuillam** [comment]
@awesomeandrey I succeed to reproduce the issue (happening in SF Cli plugin low level architecture) only when there is not default org selected when you run the command

I asked SF Cli maintainers for help, I'll keep you updated once I have a fix :)

**Comment by nvuillam** [comment]
@awesomeandrey i published an update that will avoid the crash and ask the user to run the command again, it's not perfect but it's better than the ccurrent situation, until i find how to update the auth org of the current command with SF Cli archi :)

**Comment by nvuillam** [comment]
@awesomeandrey released in 5.7.2 :)

**Comment by awesomeandrey** [comment]
@nvuillam CLI command works now!

<img width="1636" alt="hardis success" src="https://github.com/user-attachments/assets/85471dfc-f8a1-41b5-b88b-2590027ee3d6">

thank you!

**Comment by nvuillam** [comment]
@awesomeandrey great :)

If you want, don't hesitate to post about it 😇
