### ISSUE TITLE
LIMIT_EXCEEDED error when running org backup

### ISSUE THREAD

**Issue by RaviVaranasi** [hardisgroupcom/sfdx-hardis#904]
Command run: `sf hardis:org:monitor:backup -o dev-org-f /tmp/org_backup.csv -d`

```
Error (LIMIT_EXCEEDED): LIMIT_EXCEEDED: Too many files in retrieve call, limit is: 10000



Error: Command failed: sf project retrieve start -x "manifest/package-backup-items.xml" -o <user> --ignore-conflicts --wait 120
Error (LIMIT_EXCEEDED): LIMIT_EXCEEDED: Too many files in retrieve call, limit is: 10000



 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from <user>
  using the v62.0 SOAP API

 ✔ Preparing retrieve request 6ms
 ✔ Sending request to org 3.83s
 ✔ Waiting for the org to respond 16m 24.55s
 ✔ Done 0ms

 Status: Failed
 Elapsed Time: 16m 48.21s


Error (LIMIT_EXCEEDED): LIMIT_EXCEEDED: Too many files in retrieve call, limit is: 10000
```

It is a large org. Any tips on how to work around it?

**Comment by nvuillam** [comment]
You have indeed to much metadatas, it is limited to 10000 :)

But don't worry, it's handled ^^

You have a file package manifest/package-skip-items.xml

Open it and you'll see a list of metadatas types that you can uncomment to filter even more metadatas, until you have less than 10k files :)

https://sfdx-hardis.cloudity.com/hardis/org/monitor/backup/

If you are in CI and have multiple orgs to monitor, you can also define a env variable (ex: MONITORING_BACKUP_SKIP_METADATA_TYPES=CustomLabel,StaticResource,Translation )

**Comment by RaviVaranasi** [comment]
Thanks @nvuillam - Is the plan to run the command multiple times with a batch of 10K at a time?

**Comment by RaviVaranasi** [comment]
Does it fetch all the components or a diff once the first one runs successfully?

**Comment by RaviVaranasi** [comment]
One of the questions to answer if we batch 2 or 3 is whether the documentation gets overridden as opposed to merging the markdown files. For that reason, it would be helpful to to have a mode of 30k

I got it working but had to ignore the following large ones

```bash
export MONITORING_BACKUP_SKIP_METADATA_TYPES=ApexClasses,Report,Flow,ListView,Role
```

So, would we ignore the rest of the metadata we downloaded to get these as a one-off?

Apex Classes: 1327
Flow:  551
Report: 20120
ListView: 4981
Role: 4467

What would you recommend if we don't increase the limit?

**Comment by nvuillam** [comment]
Apex classes and flows are the most impacting, so you must backup them ^^

Reports... who cares ? ^^ and 20000 will take an eternity to download everytime :/

**Comment by RaviVaranasi** [comment]
Let us know when the update has been made. We can try after that.

**Comment by nvuillam** [comment]
@RaviVaranasi itns not so simple to do meanwhile you should filter to keep the most relevant metadatas :)
If you mail me your package.xml i can advise you :)

**Comment by RaviVaranasi** [comment]
@nvuillam once it downloads the metadata, does it download it again if there hasn't been an update?

**Comment by nvuillam** [comment]
@RaviVaranasi yes, because it is not possible to know before downloading that there hasn't been an update ^^

**Comment by nvuillam** [comment]
@RaviVaranasi please can you try with latest version https://github.com/hardisgroupcom/sfdx-hardis/releases/tag/v5.9.0 and provide feedback ?

`sf hardis:org:monitor:backup --full`

- no metadata filtering
- cut the huge package.xml in chunks and download them :)

**Comment by nvuillam** [comment]
I'll see what I can do
Meanwhile please can you add the following line in `.forceignore` file and try again ?

`force-app/main/default/documents/MetadataServicePatcher.document-meta.xml`

**Comment by RaviVaranasi** [comment]
That worked.

**Comment by nvuillam** [comment]
@RaviVaranasi thanks for the feedback :)

I'll update the documentation and error messages to indicate that playing with .forceignore can ignore issues, but I'll also add a --exclude-namespaces option :)

**Comment by RaviVaranasi** [comment]
@nvuillam  any update on this?

**Comment by nvuillam** [comment]
@RaviVaranasi not yet but soon :)

**Comment by nvuillam** [comment]
@RaviVaranasi it's solved and in beta, please can you confirm it's ok for your use case ? :)

```
sf plugins install sfdx-hardis@beta # or use beta docker image
sf hardis:org:monitor:backup --full --exclude-namespaces
```

**Comment by RaviVaranasi** [comment]
@nvuillam  what version is this fixed in ? 
```
❯ sf plugins install sfdx-hardis@latest

? sfdx-hardis isn't signed by Salesforce. Only install the plugin if you trust its creator. Do you want to continue the installation? yes
Because you approved this plugin, you can avoid future installation confirmations by adding the plugin to the unsignedPluginAllowList.json file. For details, see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_allowlist.htm.
Finished digital signature check.
@salesforce/cli: Installing plugin sfdx-hardis@latest... installed v5.9.0
```

**Comment by RaviVaranasi** [comment]
Never mind. I got the latest version and ran the command. It converted to 34 chunks, though I started seeing the message below.

```
Metadata API received improper input. Please ensure file name and capitalization is correct. Load of metadata from db failed for metadata of type:Dashboard and file name:xxx_Dashboards/xx_Dashboard33
```

Do you know if [PrivateConnectOutboundCalloutHourlyLimitMB limit](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_limits.htm) can be impacted by running this command? 

Also, trying to ignore metadata types by adding the following:
```
force-app/main/default/dashboards/**
```

I will report back with results

**Comment by nvuillam** [comment]
@RaviVaranasi it is solved in beta, not latest yet (there are major updates in it that I want to test before releasing)

I never saw any limit impacted by Metadata retrieves :)

About the error... I saw some of them too, in my opinion they are SF Cli / Metadata API bugs

does your .forceignore workaround work ?

**Comment by RaviVaranasi** [comment]
Below is  my`.forceignore` (way to ignore some metadata types):

```
force-app/main/default/documents/MetadataServicePatcher.document-meta.xml
force-app/main/default/dashboards
force-app/main/default/reports
```

Running into some issues where it hangs sometimes. Have you see any issues related to putting it in `.forceignore` vs ignored metadata types? I will continue running it to tweak the right set to metadata but the issue is causing some intermittent flackiness.

Ran into this issue once:
```Error (UNKNOWN_EXCEPTION): UNKNOWN_EXCEPTION: The Metadata API operation was canceled by the server```

**Comment by RaviVaranasi** [comment]
BTW, the limit issue is a non-issue.

**Comment by RaviVaranasi** [comment]
I ran with metadata using the `.forceingore.`, but it still takes time. I see a ton of empty metadata API calls. I will send over the logs

```
force-app/main/default/documents/MetadataServicePatcher.document-meta.xml
**/dashboards
**/documents
**/reports
```

What is the difference between ignoring metadata types vs `.forceignore`?

**Comment by nvuillam** [comment]
@RaviVaranasi i just checked the logs you sent, and the command works as designed, if it takes a million times it's because of the thousands of contentAssets, documents & reports

When you use .forceignore, the filtering is applied within the core of sf project retrieve start command, so it probably downloads the files even if they are matching .forceignore :/

With your 100000+ metadatas project, I think i'll need to add a new option for --full, something like `exclude-metadatas ContentAsset,Document,Report`

**Comment by RaviVaranasi** [comment]
@nvuillam, that would be awesome. I can help with development if needed.

**Comment by RaviVaranasi** [comment]
> @RaviVaranasi i just checked the logs you sent, and the command works as designed, if it takes a million times it's because of the thousands of contentAssets, documents & reports
> 
> When you use .forceignore, the filtering is applied within the core of sf project retrieve start command, so it probably downloads the files even if they are matching .forceignore :/
> 
> With your 100000+ metadatas project, I think i'll need to add a new option for --full, something like `exclude-metadatas ContentAsset,Document,Report`

Isn't `exclude-metadata` the same as `MONITORING_BACKUP_SKIP_METADATA_TYPES` ? Can we honor that value as opposed to creating a new one? The only difference is if we apply the chunking.

**Comment by nvuillam** [comment]
@RaviVaranasi it should be ok now in the newest beta,  please can you try the following ? :)

```
sf plugins install sfdx-hardis@beta
sf sf hardis:org:monitor:backup --full --exclude-namespaces --full-apply-filters
```

**Comment by RaviVaranasi** [comment]
@nvuillam  THat worked. It also generated flow documentation, but thank you for adding functionality to honor the filters. Is the plan to move it from beta to a released version?

**Comment by nvuillam** [comment]
I'm doing the last tests, and i'll release this week-end :)
