### ISSUE TITLE
How to increase wait time while running apex tests using sfdx hardis ? The default wait time is 60 minutes only.

### ISSUE THREAD

**Issue by ashishrajbanshi** [hardisgroupcom/sfdx-hardis#905]
![image](https://github.com/user-attachments/assets/0b37d9ee-72e8-48ca-8e06-80cad191b86e)
Run the apex test using sfdx hardis vs code extension.

**Comment by nvuillam** [comment]
@ashishrajbanshi as explained in the doc (https://sfdx-hardis.cloudity.com/hardis/org/test/apex/), you can define variable SFDX_TEST_WAIT_MINUTES to increase time ^^

For example:

`SFDX_TEST_WAIT_MINUTES =120 sf hardis:org:test:apex`
