### ISSUE TITLE
Scratch Org or Tracked Sandbox?

### ISSUE THREAD

**Issue by almc-c** [hardisgroupcom/sfdx-hardis#912]
When setting up a task, the prompts ask to confirm if you want to use a scratch org or a tracked sandbox org.  What if neither is true? For example: a Partial or Full Sandbox where developments occur which do not feature source tracking.

How does the response to this question alter the behavior and features of Hardis?

Can this application be used with developments in a Partial or Full SBX?

**Comment by nvuillam** [comment]
@almc-c you can technically use a partial or full sandbox, but if you do so, as tracking can't be enabled there, command [hardis:source:pull](https://sfdx-hardis.cloudity.com/hardis/scratch/pull/) (with `sf project retrieve start` in the background) won't work

To retrieve Metadatas, you'll have to manually select them using SF Extension Org Brower, or manual commands like `sf project retrieve start -m ApexClass for example`

**Comment by almc-c** [comment]
> @almc-c you can technically use a partial or full sandbox, but if you do so, as tracking can't be enabled there, command [hardis:source:pull](https://sfdx-hardis.cloudity.com/hardis/scratch/pull/) (with `sf project retrieve start` in the background) won't work
> 
> 
> 
> To retrieve Metadatas, you'll have to manually select them using SF Extension [Org Browser](https://developer.salesforce.com/docs/platform/sfvscode-extensions/guide/org-browser.html), or manual commands like `sf project retrieve start -m ApexClass for example`

Thank you. I'm going to have a go with this against a Developer Edition org and a few trailhead playground orgs.
