### ISSUE TITLE
Cant use sf hardis:org:data:import to import data to Production Org

### ISSUE THREAD

**Issue by DidZ0** [hardisgroupcom/sfdx-hardis#921]
The security prompt asks to write the org domain, while sfdx-hardis fill it with "y". 

Is it because I only use the tool without a pipeline and Org CI Auth ?

-------
=== OBJECT SET #1 STARTED
Running Plugin version: 4.37.0
Running Add-On API version: 1.6.0
[06:55:32.755] Loading Core Add-On Module declarations ...
[06:55:32.790] Connecting to the admin.mercure.iws@suez.com using SFDX sf org display ...
[06:55:35.446] Successfully connected to the admin.mercure.iws@suez.com.
[06:55:35.913] [06:55:35.913] NOTE! The Plugin has detected that you are about to modify the Production org.
To confirm that you really want to modify this org, please type:  ****.my.salesforce.com ?  y
-------

Thanks for the good work by the way 👍

**Comment by nvuillam** [comment]
@DidZ0 good catch, it's possible but not documented :)

Please add sfdmuCanModify in your .sfdx-hardis.yml config file :)

Example: `sfdmuCanModify: prod-instance.my.salesforce.com`

I'll make an update in the doc and also add the capability to define such value in an ENV variable

**Comment by nvuillam** [comment]
ps: This command has not been tested for high volumes in production yet, so be safe and repeat the operation in a full sandbox before :) (at worse it won't break anything, just fail importing files ^^ )

**Comment by nvuillam** [comment]
@DidZ0 fixed in https://github.com/hardisgroupcom/sfdx-hardis/releases/tag/v5.9.3 :)

Updated documentation: https://sfdx-hardis.cloudity.com/hardis/org/data/import/

Please let me know your feedback :)
