### ISSUE TITLE
Slack Notification on PR Validation

### ISSUE THREAD

**Issue by gustavozbulhoes** [hardisgroupcom/sfdx-hardis#944]
The sfdx-hardis integration with Slack explained in [this article](https://sfdx-hardis.cloudity.com/salesforce-ci-cd-setup-integration-slack/) is really great!
The problem is that according to my tests the notification only works for **deploy** but not for **validation**. In [check-deploy example](https://github.com/hardisgroupcom/sfdx-hardis/blob/main/defaults/ci/.github/workflows/check-deploy.yml#L68-L70) the `SLACK_TOKEN` and `SLACK_CHANNEL_ID` are defined but the notification does not work, it only works for [deploy example](https://github.com/hardisgroupcom/sfdx-hardis/blob/main/defaults/ci/.github/workflows/process-deploy.yml#L67-L68).
I would like to request to add Slack notification for `check-deploy`. 

Please let me know if I missed something on my tests or if I'm right and the slack notification only works on deploy.

**Comment by Blaze674** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by nvuillam** [comment]
@gustavozbulhoes it is by design , to not have too many notifications :)

The goal is to notify the team that something has been deployed

If you also send notifs for check deployments, you might have a messy slack channel :/

What is your requirement ?
If it is to know that a PR deployment check failed, won't it be better if you use GitHub, Gitlab, Jenkins, Azure PR-based notifications ? Which one of them are you using ? :)

**Comment by gustavozbulhoes** [comment]
That makes sense @nvuillam, thanks for sharing, I'm using Github so I will explore PR-based notifications there.
I'm closing this issue

**Comment by nvuillam** [comment]
Thanks for your understanding :)

I'm pretty sure that you can subscribe to the events you need in a dedicated slack channel ,starting from here :) https://slack.github.com/
